# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import cast
from typing import Any, Dict, List, Literal, Optional
from workos._types import _raise_deserialize_error
from workos._types import _format_datetime, _parse_datetime

from .api_key_owner import ApiKeyOwner


@dataclass(slots=True)
class ApiKey:
    """The API Key object if the value is valid, or `null` if invalid."""

    object: Literal["api_key"]
    """Distinguishes the API Key object."""
    id: str
    """Unique identifier of the API Key."""
    owner: "ApiKeyOwner"
    """The entity that owns the API Key."""
    name: str
    """A descriptive name for the API Key."""
    obfuscated_value: str
    """An obfuscated representation of the API Key value."""
    last_used_at: Optional[str]
    """Timestamp of when the API Key was last used."""
    permissions: List[str]
    """The permission slugs assigned to the API Key."""
    created_at: datetime
    """An ISO 8601 timestamp."""
    updated_at: datetime
    """An ISO 8601 timestamp."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ApiKey":
        """Deserialize from a dictionary."""
        try:
            return cls(
                object=data["object"],
                id=data["id"],
                owner=ApiKeyOwner.from_dict(cast(Dict[str, Any], data["owner"])),
                name=data["name"],
                obfuscated_value=data["obfuscated_value"],
                last_used_at=data["last_used_at"],
                permissions=data["permissions"],
                created_at=_parse_datetime(data["created_at"]),
                updated_at=_parse_datetime(data["updated_at"]),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("ApiKey", e)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["object"] = self.object
        result["id"] = self.id
        result["owner"] = self.owner.to_dict()
        result["name"] = self.name
        result["obfuscated_value"] = self.obfuscated_value
        if self.last_used_at is not None:
            result["last_used_at"] = self.last_used_at
        else:
            result["last_used_at"] = None
        result["permissions"] = self.permissions
        result["created_at"] = _format_datetime(self.created_at)
        result["updated_at"] = _format_datetime(self.updated_at)
        return result
