# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Literal
from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class ApiKeyOwner:
    """The entity that owns the API Key."""

    type: Literal["organization"]
    """The type of the API Key owner."""
    id: str
    """Unique identifier of the API Key owner."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ApiKeyOwner":
        """Deserialize from a dictionary."""
        try:
            return cls(
                type=data["type"],
                id=data["id"],
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("ApiKeyOwner", e)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["type"] = self.type
        result["id"] = self.id
        return result
