# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .agent_registration_created_data_status import AgentRegistrationCreatedDataStatus

AgentRegistrationStatus: TypeAlias = AgentRegistrationCreatedDataStatus
__all__ = ["AgentRegistrationStatus"]
