# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class AgentBlueprintCreatedDataInvocableBy:
    """Who may mint sessions from this blueprint."""

    role_slugs: list[str]
    """Role slugs whose members may mint user-delegated sessions from this blueprint."""
    organization_ids: list[str]
    """Organizations in which autonomous sessions may be minted from this blueprint."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AgentBlueprintCreatedDataInvocableBy:
        """Deserialize from a dictionary."""
        try:
            return cls(
                role_slugs=data["role_slugs"],
                organization_ids=data["organization_ids"],
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("AgentBlueprintCreatedDataInvocableBy", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        result["role_slugs"] = self.role_slugs
        result["organization_ids"] = self.organization_ids
        return result
