# This file is auto-generated by oagen. Do not edit.

"""Enumeration of agent blueprints token mint token request type values."""

from __future__ import annotations

from enum import Enum
from typing import Literal, TypeAlias


class AgentBlueprintsTokenMintTokenRequestType(str, Enum):
    """Known values for AgentBlueprintsTokenMintTokenRequestType."""

    USER_DELEGATED = "user_delegated"
    AUTONOMOUS = "autonomous"
    AGENT_DELEGATED = "agent_delegated"
    REFRESH = "refresh"

    @classmethod
    def _missing_(
        cls, value: object
    ) -> AgentBlueprintsTokenMintTokenRequestType | None:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


AgentBlueprintsTokenMintTokenRequestTypeLiteral: TypeAlias = Literal[
    "user_delegated", "autonomous", "agent_delegated", "refresh"
]
