# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Literal

from workos._types import _raise_deserialize_error

from .agent_instance_created_data_type import AgentInstanceCreatedDataType


@dataclass(slots=True)
class AgentInstanceCreatedData:
    """The event payload."""

    object: Literal["agent_instance"]
    """Distinguishes the agent instance object."""
    id: str
    """Unique identifier of the agent instance."""
    agent_blueprint_id: str
    """The agent blueprint this instance was minted from."""
    organization_id: str
    """The organization the instance acts within."""
    organization_membership_id: str | None
    """The organization membership the instance acts on behalf of; `null` for an autonomous instance."""
    type: AgentInstanceCreatedDataType
    """Whether the instance acts on behalf of a user (`delegated`) or as itself within an organization (`autonomous`)."""
    created_at: str
    """The timestamp when the agent instance was created."""
    updated_at: str
    """The timestamp when the agent instance was last updated."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AgentInstanceCreatedData:
        """Deserialize from a dictionary."""
        try:
            return cls(
                object=data.get("object", "agent_instance"),
                id=data["id"],
                agent_blueprint_id=data["agent_blueprint_id"],
                organization_id=data["organization_id"],
                organization_membership_id=data["organization_membership_id"],
                type=AgentInstanceCreatedDataType(data["type"]),
                created_at=data["created_at"],
                updated_at=data["updated_at"],
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("AgentInstanceCreatedData", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        result["object"] = self.object
        result["id"] = self.id
        result["agent_blueprint_id"] = self.agent_blueprint_id
        result["organization_id"] = self.organization_id
        if self.organization_membership_id is not None:
            result["organization_membership_id"] = self.organization_membership_id
        else:
            result["organization_membership_id"] = None
        result["type"] = self.type.value if isinstance(self.type, Enum) else self.type
        result["created_at"] = self.created_at
        result["updated_at"] = self.updated_at
        return result
