# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .connection_activated_data_status import ConnectionActivatedDataStatus

ConnectionStatus: TypeAlias = ConnectionActivatedDataStatus
__all__ = ["ConnectionStatus"]
