# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from .connection_activated_data_connection_type import (
    ConnectionActivatedDataConnectionType,
)

ConnectionDeletedDataConnectionType: TypeAlias = ConnectionActivatedDataConnectionType
__all__ = ["ConnectionDeletedDataConnectionType"]
