# This file is auto-generated by oagen. Do not edit.

"""Enumeration of connection state values."""

from __future__ import annotations

from enum import Enum
from typing import Optional
from typing import Literal, TypeAlias


class ConnectionState(str, Enum):
    """Known values for ConnectionState."""

    REQUIRES_TYPE = "requires_type"
    DRAFT = "draft"
    ACTIVE = "active"
    VALIDATING = "validating"
    INACTIVE = "inactive"
    DELETING = "deleting"

    @classmethod
    def _missing_(cls, value: object) -> Optional["ConnectionState"]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown

ConnectionStateLiteral: TypeAlias = Literal["requires_type", "draft", "active", "validating", "inactive", "deleting"]
