# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from .connection_activated_data_domain import ConnectionActivatedDataDomain

ConnectionDeactivatedDataDomain: TypeAlias = ConnectionActivatedDataDomain
