# This file is auto-generated by oagen. Do not edit.

from .create_user_invite_options_dto_locale import CreateUserInviteOptionsDtoLocale

CreateUserInviteOptionsDtoLocaleLiteral = CreateUserInviteOptionsDtoLocale
__all__ = ["CreateUserInviteOptionsDtoLocaleLiteral"]
