# This file is auto-generated by oagen. Do not edit.

"""Enumeration of data integration access token response error values."""

from __future__ import annotations

from enum import Enum
from typing import Optional
from typing import Literal, TypeAlias


class DataIntegrationAccessTokenResponseError(str, Enum):
    """Known values for DataIntegrationAccessTokenResponseError."""

    NEEDS_REAUTHORIZATION = "needs_reauthorization"
    NOT_INSTALLED = "not_installed"

    @classmethod
    def _missing_(
        cls, value: object
    ) -> Optional["DataIntegrationAccessTokenResponseError"]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


DataIntegrationAccessTokenResponseErrorLiteral: TypeAlias = Literal[
    "needs_reauthorization", "not_installed"
]
