# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class DirectoryUserEmail:
    """Directory User Email model."""

    primary: bool | None = None
    """Whether this is the primary email address."""
    type: str | None = None
    """The type of email address."""
    value: str | None = None
    """The email address value."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DirectoryUserEmail:
        """Deserialize from a dictionary."""
        try:
            return cls(
                primary=data.get("primary"),
                type=data.get("type"),
                value=data.get("value"),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("DirectoryUserEmail", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        if self.primary is not None:
            result["primary"] = self.primary
        if self.type is not None:
            result["type"] = self.type
        if self.value is not None:
            result["value"] = self.value
        else:
            result["value"] = None
        return result
