# This file is auto-generated by oagen. Do not edit.

"""Enumeration of directory user with groups state values."""

from __future__ import annotations

from enum import Enum
from typing import Optional
from typing_extensions import Literal, TypeAlias


class DirectoryUserWithGroupsState(str, Enum):
    """Known values for DirectoryUserWithGroupsState."""

    ACTIVE = "active"
    SUSPENDED = "suspended"
    INACTIVE = "inactive"

    @classmethod
    def _missing_(cls, value: object) -> Optional["DirectoryUserWithGroupsState"]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


DirectoryUserWithGroupsStateLiteral: TypeAlias = Literal[
    "active", "suspended", "inactive"
]
