# This file is auto-generated by oagen. Do not edit.

"""Enumeration of dsync activated data state values."""

from __future__ import annotations

from enum import Enum
from typing import Optional
from typing import Literal, TypeAlias


class DsyncActivatedDataState(str, Enum):
    """Known values for DsyncActivatedDataState."""

    ACTIVE = "active"
    VALIDATING = "validating"
    INVALID_CREDENTIALS = "invalid_credentials"
    INACTIVE = "inactive"
    DELETING = "deleting"

    @classmethod
    def _missing_(cls, value: object) -> Optional["DsyncActivatedDataState"]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


DsyncActivatedDataStateLiteral: TypeAlias = Literal[
    "active", "validating", "invalid_credentials", "inactive", "deleting"
]
