# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .dsync_group_user_added_data import DsyncGroupUserAddedData

DsyncGroupUserRemovedData: TypeAlias = DsyncGroupUserAddedData
