# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from .directory_user_email import DirectoryUserEmail

DsyncUserUpdatedDataEmail: TypeAlias = DirectoryUserEmail
