# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from workos.directory_sync.models.directory_group import DirectoryGroup

DsyncGroupUserRemovedDataGroup: TypeAlias = DirectoryGroup
