# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from .directory_user_state import DirectoryUserState

DsyncUserUpdatedDataState: TypeAlias = DirectoryUserState
__all__ = ["DsyncUserUpdatedDataState"]
