# This file is auto-generated by oagen. Do not edit.

"""Enumeration of dsync activated data type values."""

from __future__ import annotations

from enum import Enum
from typing import Optional
from typing_extensions import Literal, TypeAlias


class DsyncActivatedDataType(str, Enum):
    """Known values for DsyncActivatedDataType."""

    AZURE_SCIM_V_2_0 = "azure scim v2.0"
    BAMBOOHR = "bamboohr"
    BREATHE_HR = "breathe hr"
    CEZANNE_HR = "cezanne hr"
    CYBERARK_SCIM_V_2_0 = "cyberark scim v2.0"
    FOURTH_HR = "fourth hr"
    GENERIC_SCIM_V_2_0 = "generic scim v2.0"
    GSUITE_DIRECTORY = "gsuite directory"
    GUSTO = "gusto"
    HIBOB = "hibob"
    JUMP_CLOUD_SCIM_V_2_0 = "jump cloud scim v2.0"
    OKTA_SCIM_V_2_0 = "okta scim v2.0"
    ONELOGIN_SCIM_V_2_0 = "onelogin scim v2.0"
    PEOPLE_HR = "people hr"
    PERSONIO = "personio"
    PINGFEDERATE_SCIM_V_2_0 = "pingfederate scim v2.0"
    RIPPLING_SCIM_V_2_0 = "rippling scim v2.0"
    RIPPLING = "rippling"
    SAILPOINT_SCIM_V_2_0 = "sailpoint scim v2.0"
    S_3 = "s3"
    SFTP = "sftp"
    SFTP_WORKDAY = "sftp workday"
    WORKDAY = "workday"

    @classmethod
    def _missing_(cls, value: object) -> Optional["DsyncActivatedDataType"]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


DsyncActivatedDataTypeLiteral: TypeAlias = Literal[
    "azure scim v2.0",
    "bamboohr",
    "breathe hr",
    "cezanne hr",
    "cyberark scim v2.0",
    "fourth hr",
    "generic scim v2.0",
    "gsuite directory",
    "gusto",
    "hibob",
    "jump cloud scim v2.0",
    "okta scim v2.0",
    "onelogin scim v2.0",
    "people hr",
    "personio",
    "pingfederate scim v2.0",
    "rippling scim v2.0",
    "rippling",
    "sailpoint scim v2.0",
    "s3",
    "sftp",
    "sftp workday",
    "workday",
]
