# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from .dsync_activated_data_state import DsyncActivatedDataState

DsyncDeletedDataState: TypeAlias = DsyncActivatedDataState
__all__ = ["DsyncDeletedDataState"]
