# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from .flag_rule_updated_context_configured_target_user import (
    FlagRuleUpdatedContextConfiguredTargetUser,
)

FlagRuleUpdatedContextPreviousAttributeContextConfiguredTargetUser: TypeAlias = (
    FlagRuleUpdatedContextConfiguredTargetUser
)
