# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .flag_rule_updated_context_access_type import FlagRuleUpdatedContextAccessType

FlagRuleUpdatedContextPreviousAttributeContextAccessType: TypeAlias = FlagRuleUpdatedContextAccessType
__all__ = ["FlagRuleUpdatedContextPreviousAttributeContextAccessType"]
