# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from .event_context_actor_source import EventContextActorSource

FlagCreatedContextActorSource: TypeAlias = EventContextActorSource
__all__ = ["FlagCreatedContextActorSource"]
