# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from workos.feature_flags.models.feature_flag_owner import FeatureFlagOwner

FlagDeletedDataOwner: TypeAlias = FeatureFlagOwner
