# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .organization_created_data_domain_verification_strategy import (
    OrganizationCreatedDataDomainVerificationStrategy,
)

OrganizationDomainVerificationStrategy: TypeAlias = (
    OrganizationCreatedDataDomainVerificationStrategy
)
__all__ = ["OrganizationDomainVerificationStrategy"]
