# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .organization_membership_created_data_status import (
    OrganizationMembershipCreatedDataStatus,
)

OrganizationMembershipStatus: TypeAlias = OrganizationMembershipCreatedDataStatus
__all__ = ["OrganizationMembershipStatus"]
