# This file is auto-generated by oagen. Do not edit.

"""Enumeration of organization domain data dto state values."""

from __future__ import annotations

from enum import Enum
from typing import Optional
from typing_extensions import Literal, TypeAlias


class OrganizationDomainDataDtoState(str, Enum):
    """Known values for OrganizationDomainDataDtoState."""

    PENDING = "pending"
    VERIFIED = "verified"

    @classmethod
    def _missing_(cls, value: object) -> Optional["OrganizationDomainDataDtoState"]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


OrganizationDomainDataDtoStateLiteral: TypeAlias = Literal["pending", "verified"]
