# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from .password_reset_created_data import PasswordResetCreatedData

PasswordResetSucceededData: TypeAlias = PasswordResetCreatedData
