# This file is auto-generated by oagen. Do not edit.

from .create_user_dto_password_hash_type import CreateUserDtoPasswordHashType

PasswordHashType = CreateUserDtoPasswordHashType
__all__ = ["PasswordHashType"]
