# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .create_connection_oidc_options_id_token_signature_algorithm import (
    CreateConnectionOIDCOptionsIdTokenSignatureAlgorithm,
)

PatchConnectionOIDCOptionsIdTokenSignatureAlgorithm: TypeAlias = (
    CreateConnectionOIDCOptionsIdTokenSignatureAlgorithm
)
__all__ = ["PatchConnectionOIDCOptionsIdTokenSignatureAlgorithm"]
