# This file is auto-generated by oagen. Do not edit.

"""Enumeration of radar standalone assess request action values."""

from __future__ import annotations

from enum import Enum
from typing import Optional
from typing import Literal, TypeAlias


class RadarStandaloneAssessRequestAction(str, Enum):
    """Known values for RadarStandaloneAssessRequestAction."""

    SIGN_UP = "sign-up"
    SIGN_IN = "sign-in"

    @classmethod
    def _missing_(cls, value: object) -> Optional["RadarStandaloneAssessRequestAction"]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


RadarStandaloneAssessRequestActionLiteral: TypeAlias = Literal["sign-up", "sign-in"]
