# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .create_user_invite_options_locale import CreateUserInviteOptionsLocale

ResendUserInviteOptionsLocale: TypeAlias = CreateUserInviteOptionsLocale
__all__ = ["ResendUserInviteOptionsLocale"]
