# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any

from workos._types import _raise_deserialize_error

from .resource_export_completed_data_resource_type import (
    ResourceExportCompletedDataResourceType,
)


@dataclass(slots=True)
class ResourceExportCompletedData:
    """The event payload."""

    id: str
    """The ID of the resource export."""
    resource_type: ResourceExportCompletedDataResourceType
    """The type of resource being exported."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ResourceExportCompletedData:
        """Deserialize from a dictionary."""
        try:
            return cls(
                id=data["id"],
                resource_type=ResourceExportCompletedDataResourceType(
                    data["resource_type"]
                ),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("ResourceExportCompletedData", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        result["id"] = self.id
        result["resource_type"] = (
            self.resource_type.value
            if isinstance(self.resource_type, Enum)
            else self.resource_type
        )
        return result
