# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .authenticate_response_impersonator import AuthenticateResponseImpersonator

SessionRevokedDataImpersonator: TypeAlias = AuthenticateResponseImpersonator
