# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .session_created_data_auth_method import SessionCreatedDataAuthMethod

SessionRevokedDataAuthMethod: TypeAlias = SessionCreatedDataAuthMethod
__all__ = ["SessionRevokedDataAuthMethod"]
