# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from .create_webhook_endpoint_events import CreateWebhookEndpointEvents

UpdateWebhookEndpointEvents: TypeAlias = CreateWebhookEndpointEvents
__all__ = ["UpdateWebhookEndpointEvents"]
