# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .custom_provider_definition_authenticate_via import (
    CustomProviderDefinitionAuthenticateVia,
)

UpdateCustomProviderDefinitionAuthenticateVia: TypeAlias = (
    CustomProviderDefinitionAuthenticateVia
)
__all__ = ["UpdateCustomProviderDefinitionAuthenticateVia"]
