# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .vault_data_created_data_actor_source import VaultDataCreatedDataActorSource

VaultNamesListedDataActorSource: TypeAlias = VaultDataCreatedDataActorSource
__all__ = ["VaultNamesListedDataActorSource"]
