# This file is auto-generated by oagen. Do not edit.

"""Enumeration of vault data created data actor source values."""

from __future__ import annotations

from enum import Enum
from typing import Literal, TypeAlias


class VaultDataCreatedDataActorSource(str, Enum):
    """Known values for VaultDataCreatedDataActorSource."""

    API = "api"
    DASHBOARD = "dashboard"

    @classmethod
    def _missing_(cls, value: object) -> VaultDataCreatedDataActorSource | None:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


VaultDataCreatedDataActorSourceLiteral: TypeAlias = Literal["api", "dashboard"]
