# This file is auto-generated by oagen. Do not edit.

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from workos.user_management.models.user_management_waitlists_state import (
        UserManagementWaitlistsState as WaitlistEntryState,
    )
else:

    def __getattr__(name: str):
        if name == "WaitlistEntryState":
            from workos.user_management.models.user_management_waitlists_state import (
                UserManagementWaitlistsState,
            )

            return UserManagementWaitlistsState
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = ["WaitlistEntryState"]
