# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from .update_webhook_endpoint_status import UpdateWebhookEndpointStatus

WebhookEndpointStatus: TypeAlias = UpdateWebhookEndpointStatus
__all__ = ["WebhookEndpointStatus"]
