# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import cast
from typing import Any, Dict
from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class RadarStandaloneDeleteRadarListEntryRequest:
    """Radar Standalone Delete Radar List Entry Request model."""

    entry: str
    """The value to remove from the list. Must match an existing entry."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "RadarStandaloneDeleteRadarListEntryRequest":
        """Deserialize from a dictionary."""
        try:
            return cls(
                entry=data["entry"],
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("RadarStandaloneDeleteRadarListEntryRequest", e)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["entry"] = self.entry
        return result
