# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from workos.common.models.connection_activated_data_domain import ConnectionActivatedDataDomain

ConnectionDomain: TypeAlias = ConnectionActivatedDataDomain
