# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, cast

from workos._types import _raise_deserialize_error

from .create_connection_key_pair import CreateConnectionKeyPair


@dataclass(slots=True)
class CreateConnectionSAMLOptions:
    """Create Connection SAML Options model."""

    idp_metadata_url: str | None = None
    """The Identity Provider metadata URL. When provided, the IdP fields and signing certificates are imported from the metadata document. Mutually exclusive with the manual IdP fields."""
    acs_url: str | None = None
    """A custom Assertion Consumer Service (ACS) URL override. When omitted, the standard WorkOS-generated ACS URL is used."""
    sp_entity_id: str | None = None
    """A custom Service Provider Entity ID (audience) override. When omitted, the connection external key is used."""
    idp_entity_id: str | None = None
    """The Identity Provider Entity ID."""
    idp_sso_url: str | None = None
    """The Identity Provider SSO URL. Required when configuring the connection with manual IdP fields."""
    idp_signing_certs: list[str] | None = None
    """The X.509 certificates used to verify signed SAML responses from the Identity Provider. Required when configuring the connection with manual IdP fields."""
    sp_signing_key_pair: CreateConnectionKeyPair | None = None
    """The customer-owned key pair used to sign SAML requests sent to the Identity Provider. When omitted, WorkOS generates and manages the signing key pair."""
    sp_encryption_key_pairs: list[CreateConnectionKeyPair] | None = None
    """The customer-owned key pairs used to decrypt encrypted SAML responses from the Identity Provider. When omitted, WorkOS generates and manages the encryption key pair."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CreateConnectionSAMLOptions:
        """Deserialize from a dictionary."""
        try:
            return cls(
                idp_metadata_url=data.get("idp_metadata_url"),
                acs_url=data.get("acs_url"),
                sp_entity_id=data.get("sp_entity_id"),
                idp_entity_id=data.get("idp_entity_id"),
                idp_sso_url=data.get("idp_sso_url"),
                idp_signing_certs=data.get("idp_signing_certs"),
                sp_signing_key_pair=CreateConnectionKeyPair.from_dict(
                    cast(dict[str, Any], _v_sp_signing_key_pair)
                )
                if (_v_sp_signing_key_pair := data.get("sp_signing_key_pair"))
                is not None
                else None,
                sp_encryption_key_pairs=[
                    CreateConnectionKeyPair.from_dict(cast(dict[str, Any], item))
                    for item in cast(list[Any], _v_sp_encryption_key_pairs)
                ]
                if (_v_sp_encryption_key_pairs := data.get("sp_encryption_key_pairs"))
                is not None
                else None,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("CreateConnectionSAMLOptions", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        if self.idp_metadata_url is not None:
            result["idp_metadata_url"] = self.idp_metadata_url
        if self.acs_url is not None:
            result["acs_url"] = self.acs_url
        if self.sp_entity_id is not None:
            result["sp_entity_id"] = self.sp_entity_id
        if self.idp_entity_id is not None:
            result["idp_entity_id"] = self.idp_entity_id
        if self.idp_sso_url is not None:
            result["idp_sso_url"] = self.idp_sso_url
        if self.idp_signing_certs is not None:
            result["idp_signing_certs"] = self.idp_signing_certs
        if self.sp_signing_key_pair is not None:
            result["sp_signing_key_pair"] = self.sp_signing_key_pair.to_dict()
        if self.sp_encryption_key_pairs is not None:
            result["sp_encryption_key_pairs"] = [
                item.to_dict() for item in self.sp_encryption_key_pairs
            ]
        return result
