# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, cast

from workos._types import _raise_deserialize_error

from .create_connection_standard_attributes import CreateConnectionStandardAttributes


@dataclass(slots=True)
class CreateConnectionAttributeMaps:
    """Create Connection Attribute Maps model."""

    standard_attributes: CreateConnectionStandardAttributes | None = None
    """How IdP attributes or claims map onto the standard WorkOS profile fields. Provided fields override the defaults for the connection type."""
    custom_attributes: dict[str, str] | None = None
    """How IdP attributes or claims map onto custom attributes, keyed by custom attribute name. Custom attributes must already be defined in the WorkOS dashboard."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CreateConnectionAttributeMaps:
        """Deserialize from a dictionary."""
        try:
            return cls(
                standard_attributes=CreateConnectionStandardAttributes.from_dict(
                    cast(dict[str, Any], _v_standard_attributes)
                )
                if (_v_standard_attributes := data.get("standard_attributes"))
                is not None
                else None,
                custom_attributes=data.get("custom_attributes"),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("CreateConnectionAttributeMaps", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        if self.standard_attributes is not None:
            result["standard_attributes"] = self.standard_attributes.to_dict()
        if self.custom_attributes is not None:
            result["custom_attributes"] = self.custom_attributes
        return result
