# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class PatchConnectionSAMLOptions:
    """Patch Connection SAML Options model."""

    idp_metadata_url: str | None = None
    """The Identity Provider metadata URL. When provided, the IdP fields and signing certificates are re-imported from the metadata document, replacing the current set. Mutually exclusive with the manual IdP fields. Set to `null` to stop tracking a metadata URL."""
    acs_url: str | None = None
    """A custom Assertion Consumer Service (ACS) URL override. Set to `null` to revert to the standard WorkOS-generated ACS URL."""
    sp_entity_id: str | None = None
    """A custom Service Provider Entity ID (audience) override. Set to `null` to revert to the connection external key."""
    idp_entity_id: str | None = None
    """The Identity Provider Entity ID."""
    idp_sso_url: str | None = None
    """The Identity Provider SSO URL."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> PatchConnectionSAMLOptions:
        """Deserialize from a dictionary."""
        try:
            return cls(
                idp_metadata_url=data.get("idp_metadata_url"),
                acs_url=data.get("acs_url"),
                sp_entity_id=data.get("sp_entity_id"),
                idp_entity_id=data.get("idp_entity_id"),
                idp_sso_url=data.get("idp_sso_url"),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("PatchConnectionSAMLOptions", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        if self.idp_metadata_url is not None:
            result["idp_metadata_url"] = self.idp_metadata_url
        else:
            result["idp_metadata_url"] = None
        if self.acs_url is not None:
            result["acs_url"] = self.acs_url
        else:
            result["acs_url"] = None
        if self.sp_entity_id is not None:
            result["sp_entity_id"] = self.sp_entity_id
        else:
            result["sp_entity_id"] = None
        if self.idp_entity_id is not None:
            result["idp_entity_id"] = self.idp_entity_id
        if self.idp_sso_url is not None:
            result["idp_sso_url"] = self.idp_sso_url
        return result
