# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, cast

from workos._types import _raise_deserialize_error

from .patch_connection_attribute_maps import PatchConnectionAttributeMaps
from .patch_connection_oidc_options import PatchConnectionOIDCOptions
from .patch_connection_saml_options import PatchConnectionSAMLOptions


@dataclass(slots=True)
class PatchConnection:
    """Patch Connection model."""

    name: str | None = None
    """A human-readable name for the Connection."""
    external_id: str | None = None
    """The customer-owned identifier for the Connection. Set to `null` to stop tracking one."""
    connection_type: str | None = None
    """The type of the Connection. Immutable after creation — it may be sent, but only with the Connection current type."""
    attribute_maps: PatchConnectionAttributeMaps | None = None
    """How IdP attributes or claims map onto WorkOS profile fields. Only the provided fields are updated."""
    saml_options: PatchConnectionSAMLOptions | None = None
    """Protocol configuration for SAML connections. Only the provided fields are updated. Mutually exclusive with `oidc_options`."""
    oidc_options: PatchConnectionOIDCOptions | None = None
    """Protocol configuration for OIDC connections. Only the provided fields are updated. Mutually exclusive with `saml_options`."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> PatchConnection:
        """Deserialize from a dictionary."""
        try:
            return cls(
                name=data.get("name"),
                external_id=data.get("external_id"),
                connection_type=data.get("connection_type"),
                attribute_maps=PatchConnectionAttributeMaps.from_dict(
                    cast(dict[str, Any], _v_attribute_maps)
                )
                if (_v_attribute_maps := data.get("attribute_maps")) is not None
                else None,
                saml_options=PatchConnectionSAMLOptions.from_dict(
                    cast(dict[str, Any], _v_saml_options)
                )
                if (_v_saml_options := data.get("saml_options")) is not None
                else None,
                oidc_options=PatchConnectionOIDCOptions.from_dict(
                    cast(dict[str, Any], _v_oidc_options)
                )
                if (_v_oidc_options := data.get("oidc_options")) is not None
                else None,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("PatchConnection", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        if self.name is not None:
            result["name"] = self.name
        if self.external_id is not None:
            result["external_id"] = self.external_id
        else:
            result["external_id"] = None
        if self.connection_type is not None:
            result["connection_type"] = self.connection_type
        if self.attribute_maps is not None:
            result["attribute_maps"] = self.attribute_maps.to_dict()
        if self.saml_options is not None:
            result["saml_options"] = self.saml_options.to_dict()
        if self.oidc_options is not None:
            result["oidc_options"] = self.oidc_options.to_dict()
        return result
