# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, cast

from workos._types import _raise_deserialize_error

from .saml_idp_signing_certificate import SAMLIdpSigningCertificate


@dataclass(slots=True)
class SAMLIdpSigningCertificateList:
    """SAML Idp Signing Certificate List model."""

    object: Literal["list"]
    data: list[SAMLIdpSigningCertificate]
    """Every Identity Provider signing certificate on the Connection, including expired ones, oldest first."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> SAMLIdpSigningCertificateList:
        """Deserialize from a dictionary."""
        try:
            return cls(
                object=data.get("object", "list"),
                data=[
                    SAMLIdpSigningCertificate.from_dict(cast(dict[str, Any], item))
                    for item in cast(list[Any], data["data"])
                ],
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("SAMLIdpSigningCertificateList", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        result["object"] = self.object
        result["data"] = [item.to_dict() for item in self.data]
        return result
