# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import cast
from typing import Any, Dict
from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class SSOAuthorizeUrlResponse:
    """SSO Authorize Url Response model."""

    url: str
    """An OAuth 2.0 authorization URL."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SSOAuthorizeUrlResponse":
        """Deserialize from a dictionary."""
        try:
            return cls(
                url=data["url"],
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("SSOAuthorizeUrlResponse", e)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["url"] = self.url
        return result
