# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import cast
from typing import Any, Dict, List, Literal, Optional
from workos._errors import BaseRequestException

from .audit_log_schema_json_actor import AuditLogSchemaJsonActor
from .audit_log_schema_json_target import AuditLogSchemaJsonTarget


@dataclass(slots=True)
class AuditLogSchemaJson:
    """The schema associated with the action."""

    object: Literal["audit_log_schema"]
    """Distinguishes the Audit Log Schema object."""
    version: int
    """The version of the schema."""
    targets: List["AuditLogSchemaJsonTarget"]
    """The list of targets for the schema."""
    created_at: datetime
    """The timestamp when the Audit Log Schema was created."""
    actor: Optional["AuditLogSchemaJsonActor"] = None
    """The metadata schema for the actor."""
    metadata: Optional[Dict[str, Any]] = None
    """Additional data associated with the event or entity."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AuditLogSchemaJson":
        """Deserialize from a dictionary."""
        try:
            return cls(
                object=data["object"],
                version=data["version"],
                targets=[
                    AuditLogSchemaJsonTarget.from_dict(cast(Dict[str, Any], item))
                    for item in cast(list[Any], data["targets"])
                ],
                created_at=datetime.fromisoformat(
                    data["created_at"].replace("Z", "+00:00")
                ),
                actor=AuditLogSchemaJsonActor.from_dict(cast(Dict[str, Any], _v))
                if (_v := data.get("actor")) is not None
                else None,
                metadata=data.get("metadata"),
            )
        except (KeyError, ValueError) as e:
            raise BaseRequestException(
                f"Unexpected API response while parsing AuditLogSchemaJson: {e!s}"
            ) from e

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["object"] = self.object
        result["version"] = self.version
        result["targets"] = [item.to_dict() for item in self.targets]
        result["created_at"] = self.created_at.isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")
        if self.actor is not None:
            result["actor"] = self.actor.to_dict()
        if self.metadata is not None:
            result["metadata"] = self.metadata
        return result
