# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, cast

from workos._types import _format_datetime, _parse_datetime, _raise_deserialize_error

from .audit_log_event_actor import AuditLogEventActor
from .audit_log_event_context import AuditLogEventContext
from .audit_log_event_target import AuditLogEventTarget


@dataclass(slots=True)
class AuditLogEvent:
    """Audit Log Event model."""

    action: str
    """Identifier of what happened."""
    occurred_at: datetime
    """ISO-8601 value of when the action occurred."""
    actor: AuditLogEventActor
    """The entity that performed the action."""
    targets: list[AuditLogEventTarget]
    """The resources affected by the action."""
    context: AuditLogEventContext
    """Additional context about where and how the action occurred."""
    metadata: dict[str, str | float | bool] | None = None
    """Additional data associated with the event or entity."""
    version: int | None = None
    """What schema version the event is associated with."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AuditLogEvent:
        """Deserialize from a dictionary."""
        try:
            return cls(
                action=data["action"],
                occurred_at=_parse_datetime(data["occurred_at"]),
                actor=AuditLogEventActor.from_dict(cast(dict[str, Any], data["actor"])),
                targets=[
                    AuditLogEventTarget.from_dict(cast(dict[str, Any], item))
                    for item in cast(list[Any], data["targets"])
                ],
                context=AuditLogEventContext.from_dict(
                    cast(dict[str, Any], data["context"])
                ),
                metadata=data.get("metadata"),
                version=data.get("version"),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("AuditLogEvent", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        result["action"] = self.action
        result["occurred_at"] = _format_datetime(self.occurred_at)
        result["actor"] = self.actor.to_dict()
        result["targets"] = [item.to_dict() for item in self.targets]
        result["context"] = self.context.to_dict()
        if self.metadata is not None:
            result["metadata"] = self.metadata
        if self.version is not None:
            result["version"] = self.version
        return result
