from typing import Literal, TypeVar

# README
# When adding a new event type, ensure a new event class is created
# and added to the Event class union type in event.py.

EventType = Literal[
    "api_key.created",
    "api_key.revoked",
    "authentication.email_verification_failed",
    "authentication.email_verification_succeeded",
    "authentication.magic_auth_failed",
    "authentication.magic_auth_succeeded",
    "authentication.mfa_failed",
    "authentication.mfa_succeeded",
    "authentication.oauth_failed",
    "authentication.oauth_succeeded",
    "authentication.passkey_failed",
    "authentication.passkey_succeeded",
    "authentication.password_failed",
    "authentication.password_succeeded",
    "authentication.radar_risk_detected",
    "authentication.sso_failed",
    "authentication.sso_succeeded",
    "connection.activated",
    "connection.deactivated",
    "connection.deleted",
    "connection.saml_certificate_renewed",
    "connection.saml_certificate_renewal_required",
    "dsync.activated",
    "dsync.deleted",
    "dsync.group.created",
    "dsync.group.deleted",
    "dsync.group.updated",
    "dsync.user.created",
    "dsync.user.deleted",
    "dsync.user.updated",
    "dsync.group.user_added",
    "dsync.group.user_removed",
    "email_verification.created",
    "flag.created",
    "flag.deleted",
    "flag.rule_updated",
    "flag.updated",
    "invitation.accepted",
    "invitation.created",
    "invitation.resent",
    "invitation.revoked",
    "magic_auth.created",
    "organization.created",
    "organization.deleted",
    "organization.updated",
    "organization_domain.verification_failed",
    "organization_domain.verified",
    "organization_domain.created",
    "organization_domain.deleted",
    "organization_domain.updated",
    "organization_membership.created",
    "organization_membership.deleted",
    "organization_membership.updated",
    "organization_role.created",
    "organization_role.updated",
    "organization_role.deleted",
    "password_reset.created",
    "password_reset.succeeded",
    "permission.created",
    "permission.updated",
    "permission.deleted",
    "role.created",
    "role.deleted",
    "role.updated",
    "session.created",
    "session.revoked",
    "user.created",
    "user.deleted",
    "user.updated",
]

EventTypeDiscriminator = TypeVar("EventTypeDiscriminator", bound=EventType)
