# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import cast
from typing import Any, Dict
from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class PortalLinkResponse:
    """Portal Link Response model."""

    link: str
    """An ephemeral link to initiate the Admin Portal."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PortalLinkResponse":
        """Deserialize from a dictionary."""
        try:
            return cls(
                link=data["link"],
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("PortalLinkResponse", e)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["link"] = self.link
        return result
