# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import cast
from typing import Any, Dict, Literal, Optional
from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class SSOIntentOptions:
    """SSO Intent Options model."""

    bookmark_slug: Optional[str] = None
    """The bookmark slug to use for SSO."""
    provider_type: Optional[Literal["GoogleSAML"]] = None
    """The SSO provider type to configure."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SSOIntentOptions":
        """Deserialize from a dictionary."""
        try:
            return cls(
                bookmark_slug=data.get("bookmark_slug"),
                provider_type=data.get("provider_type"),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("SSOIntentOptions", e)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        if self.bookmark_slug is not None:
            result["bookmark_slug"] = self.bookmark_slug
        if self.provider_type is not None:
            result["provider_type"] = self.provider_type
        return result
