# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Literal, Optional
from workos._errors import BaseRequestException
from workos.common.models import DataIntegrationsListResponseDataConnectedAccountState


@dataclass(slots=True)
class DataIntegrationsListResponseDataConnectedAccount:
    """Data Integrations List Response Data Connected Account model."""

    object: Literal["connected_account"]
    """Distinguishes the connected account object."""
    id: str
    """The unique identifier of the connected account."""
    user_id: Optional[str]
    """The [User](https://workos.com/docs/reference/authkit/user) identifier associated with this connection."""
    organization_id: Optional[str]
    """The [Organization](https://workos.com/docs/reference/organization) identifier associated with this connection, or `null` if not scoped to an organization."""
    scopes: List[str]
    """The OAuth scopes granted for this connection."""
    state: "DataIntegrationsListResponseDataConnectedAccountState"
    """The state of the connected account:
- `connected`: The connection is active and tokens are valid.
- `needs_reauthorization`: The user needs to reauthorize the connection, typically because required scopes have changed.
- `disconnected`: The connection has been disconnected."""
    created_at: str
    """The timestamp when the connection was created."""
    updated_at: str
    """The timestamp when the connection was last updated."""
    userland_user_id: Optional[str] = None
    """Use `user_id` instead."""

    @classmethod
    def from_dict(
        cls, data: Dict[str, Any]
    ) -> "DataIntegrationsListResponseDataConnectedAccount":
        """Deserialize from a dictionary."""
        try:
            return cls(
                object=data["object"],
                id=data["id"],
                user_id=data["user_id"],
                organization_id=data["organization_id"],
                scopes=data["scopes"],
                state=DataIntegrationsListResponseDataConnectedAccountState(
                    data["state"]
                ),
                created_at=data["created_at"],
                updated_at=data["updated_at"],
                userland_user_id=data.get("userlandUserId"),
            )
        except (KeyError, ValueError) as e:
            raise BaseRequestException(
                f"Unexpected API response while parsing DataIntegrationsListResponseDataConnectedAccount: {e!s}"
            ) from e

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["object"] = self.object
        result["id"] = self.id
        if self.user_id is not None:
            result["user_id"] = self.user_id
        else:
            result["user_id"] = None
        if self.organization_id is not None:
            result["organization_id"] = self.organization_id
        else:
            result["organization_id"] = None
        result["scopes"] = self.scopes
        result["state"] = self.state
        result["created_at"] = self.created_at
        result["updated_at"] = self.updated_at
        if self.userland_user_id is not None:
            result["userlandUserId"] = self.userland_user_id
        else:
            result["userlandUserId"] = None
        return result
