# This file is auto-generated by oagen. Do not edit.

import json

import pytest

from tests.generated_helpers import load_fixture
from workos import AsyncWorkOSClient, WorkOSClient
from workos._errors import (
    AuthenticationError,
    BadRequestError,
    NotFoundError,
    RateLimitExceededError,
    ServerError,
    UnprocessableEntityError,
)
from workos.platform_teams.models import Team


class TestPlatformTeams:
    def test_create_team(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("team.json"),
        )
        result = workos.platform_teams.create_team(
            admin_email="test_admin_email", name="test_name"
        )
        assert isinstance(result, Team)
        assert result.object == "team"
        assert result.id == "team_01JX9AN6E02HAG2Q2CKGC1XT5W"
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/platform/teams")
        body = json.loads(request.content)
        assert body["admin_email"] == "test_admin_email"
        assert body["name"] == "test_name"

    def test_get_team(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("team.json"),
        )
        result = workos.platform_teams.get_team("test_team_id")
        assert isinstance(result, Team)
        assert result.object == "team"
        assert result.id == "team_01JX9AN6E02HAG2Q2CKGC1XT5W"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/platform/teams/test_team_id")

    def test_create_team_with_request_options(self, workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("team.json"))
        workos.platform_teams.create_team(
            admin_email="test_admin_email",
            name="test_name",
            request_options={"extra_headers": {"X-Custom": "value"}},
        )
        request = httpx_mock.get_request()
        assert request.headers["X-Custom"] == "value"

    def test_create_team_unauthorized(self, workos, httpx_mock):
        httpx_mock.add_response(
            status_code=401,
            json={"message": "Unauthorized"},
        )
        with pytest.raises(AuthenticationError):
            workos.platform_teams.create_team(
                admin_email="test_admin_email", name="test_name"
            )

    def test_create_team_not_found(self, httpx_mock):
        workos = WorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundError):
                workos.platform_teams.create_team(
                    admin_email="test_admin_email", name="test_name"
                )
        finally:
            workos.close()

    def test_create_team_rate_limited(self, httpx_mock):
        workos = WorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededError):
                workos.platform_teams.create_team(
                    admin_email="test_admin_email", name="test_name"
                )
        finally:
            workos.close()

    def test_create_team_server_error(self, httpx_mock):
        workos = WorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerError):
                workos.platform_teams.create_team(
                    admin_email="test_admin_email", name="test_name"
                )
        finally:
            workos.close()

    def test_create_team_bad_request(self, httpx_mock):
        workos = WorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=400, json={"message": "Bad request"})
            with pytest.raises(BadRequestError):
                workos.platform_teams.create_team(
                    admin_email="test_admin_email", name="test_name"
                )
        finally:
            workos.close()

    def test_create_team_unprocessable(self, httpx_mock):
        workos = WorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=422, json={"message": "Unprocessable"})
            with pytest.raises(UnprocessableEntityError):
                workos.platform_teams.create_team(
                    admin_email="test_admin_email", name="test_name"
                )
        finally:
            workos.close()


class TestAsyncPlatformTeams:
    @pytest.mark.asyncio
    async def test_create_team(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("team.json"))
        result = await async_workos.platform_teams.create_team(
            admin_email="test_admin_email", name="test_name"
        )
        assert isinstance(result, Team)
        assert result.object == "team"
        assert result.id == "team_01JX9AN6E02HAG2Q2CKGC1XT5W"
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/platform/teams")

    @pytest.mark.asyncio
    async def test_get_team(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("team.json"))
        result = await async_workos.platform_teams.get_team("test_team_id")
        assert isinstance(result, Team)
        assert result.object == "team"
        assert result.id == "team_01JX9AN6E02HAG2Q2CKGC1XT5W"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/platform/teams/test_team_id")

    @pytest.mark.asyncio
    async def test_create_team_with_request_options(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("team.json"))
        await async_workos.platform_teams.create_team(
            admin_email="test_admin_email",
            name="test_name",
            request_options={"extra_headers": {"X-Custom": "value"}},
        )
        request = httpx_mock.get_request()
        assert request.headers["X-Custom"] == "value"

    @pytest.mark.asyncio
    async def test_create_team_unauthorized(self, async_workos, httpx_mock):
        httpx_mock.add_response(status_code=401, json={"message": "Unauthorized"})
        with pytest.raises(AuthenticationError):
            await async_workos.platform_teams.create_team(
                admin_email="test_admin_email", name="test_name"
            )

    @pytest.mark.asyncio
    async def test_create_team_not_found(self, httpx_mock):
        workos = AsyncWorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundError):
                await workos.platform_teams.create_team(
                    admin_email="test_admin_email", name="test_name"
                )
        finally:
            await workos.close()

    @pytest.mark.asyncio
    async def test_create_team_rate_limited(self, httpx_mock):
        workos = AsyncWorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededError):
                await workos.platform_teams.create_team(
                    admin_email="test_admin_email", name="test_name"
                )
        finally:
            await workos.close()

    @pytest.mark.asyncio
    async def test_create_team_server_error(self, httpx_mock):
        workos = AsyncWorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerError):
                await workos.platform_teams.create_team(
                    admin_email="test_admin_email", name="test_name"
                )
        finally:
            await workos.close()

    @pytest.mark.asyncio
    async def test_create_team_bad_request(self, httpx_mock):
        workos = AsyncWorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=400, json={"message": "Bad request"})
            with pytest.raises(BadRequestError):
                await workos.platform_teams.create_team(
                    admin_email="test_admin_email", name="test_name"
                )
        finally:
            await workos.close()

    @pytest.mark.asyncio
    async def test_create_team_unprocessable(self, httpx_mock):
        workos = AsyncWorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=422, json={"message": "Unprocessable"})
            with pytest.raises(UnprocessableEntityError):
                await workos.platform_teams.create_team(
                    admin_email="test_admin_email", name="test_name"
                )
        finally:
            await workos.close()
