# This file is auto-generated by oagen. Do not edit.

"""Client tests: retries, errors, context manager, idempotency."""

import httpx
import pytest

from workos import WorkOS, AsyncWorkOS
from workos import _client as generated_client_module
from workos._errors import (
    AuthenticationException,
    BadRequestException,
    AuthorizationException,
    NotFoundException,
    ConflictException,
    UnprocessableEntityException,
    RateLimitExceededException,
    ServerException,
)


class TestWorkOSClient:
    def test_missing_credentials_raise(self):
        with pytest.raises(ValueError):
            WorkOS()

    def test_context_manager(self):
        with WorkOS(api_key="sk_test_123", client_id="client_test") as client:
            assert client._api_key == "sk_test_123"

    def test_api_key_only_initializes(self):
        client = WorkOS(api_key="sk_test_123")
        assert client._api_key == "sk_test_123"
        assert client.client_id is None
        client.close()

    def test_client_id_from_constructor(self):
        client = WorkOS(client_id="client_test_456")
        assert client.client_id == "client_test_456"
        assert client._api_key is None
        client.close()

    def test_raises_400(self, httpx_mock):
        httpx_mock.add_response(
            status_code=400,
            json={"message": "Error"},
        )
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(BadRequestException):
            client.request("GET", "test")
        client.close()

    def test_raises_401(self, httpx_mock):
        httpx_mock.add_response(
            status_code=401,
            json={"message": "Error"},
        )
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(AuthenticationException):
            client.request("GET", "test")
        client.close()

    def test_raises_403(self, httpx_mock):
        httpx_mock.add_response(
            status_code=403,
            json={"message": "Error"},
        )
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(AuthorizationException):
            client.request("GET", "test")
        client.close()

    def test_raises_404(self, httpx_mock):
        httpx_mock.add_response(
            status_code=404,
            json={"message": "Error"},
        )
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(NotFoundException):
            client.request("GET", "test")
        client.close()

    def test_raises_409(self, httpx_mock):
        httpx_mock.add_response(
            status_code=409,
            json={"message": "Error"},
        )
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(ConflictException):
            client.request("GET", "test")
        client.close()

    def test_raises_422(self, httpx_mock):
        httpx_mock.add_response(
            status_code=422,
            json={"message": "Error"},
        )
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(UnprocessableEntityException):
            client.request("GET", "test")
        client.close()

    def test_raises_429(self, httpx_mock):
        httpx_mock.add_response(
            status_code=429,
            json={"message": "Error"},
        )
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(RateLimitExceededException):
            client.request("GET", "test")
        client.close()

    def test_raises_500(self, httpx_mock):
        httpx_mock.add_response(
            status_code=500,
            json={"message": "Error"},
        )
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(ServerException):
            client.request("GET", "test")
        client.close()

    def test_idempotency_key_on_post(self, httpx_mock):
        httpx_mock.add_response(json={})
        client = WorkOS(api_key="sk_test_123", client_id="client_test")
        client.request("POST", "test")
        request = httpx_mock.get_request()
        assert "Idempotency-Key" in request.headers
        client.close()

    def test_no_idempotency_key_on_get(self, httpx_mock):
        httpx_mock.add_response(json={})
        client = WorkOS(api_key="sk_test_123", client_id="client_test")
        client.request("GET", "test")
        request = httpx_mock.get_request()
        assert "Idempotency-Key" not in request.headers
        client.close()

    def test_no_authorization_header_without_api_key(self, httpx_mock):
        httpx_mock.add_response(json={})
        client = WorkOS(client_id="client_test")
        client.request("GET", "test")
        request = httpx_mock.get_request()
        assert "Authorization" not in request.headers
        client.close()

    def test_empty_body_sends_json(self, httpx_mock):
        httpx_mock.add_response(json={})
        client = WorkOS(api_key="sk_test_123", client_id="client_test")
        client.request("PUT", "test", body={})
        request = httpx_mock.get_request()
        assert request.content == b"{}"
        client.close()

    def test_calculate_retry_delay_uses_retry_after_seconds(self):
        assert WorkOS._calculate_retry_delay(1, "30") == 30.0

    def test_retry_exhaustion_raises_rate_limit(self, httpx_mock, monkeypatch):
        monkeypatch.setattr(generated_client_module.time, "sleep", lambda _: None)
        for _ in range(4):
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=3)
        with pytest.raises(RateLimitExceededException):
            client.request("GET", "test")
        client.close()

    def test_rate_limit_retry_after_is_parsed(self, httpx_mock):
        httpx_mock.add_response(
            status_code=429,
            headers={"Retry-After": "30"},
            json={"message": "Slow down"},
        )
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(RateLimitExceededException) as exc_info:
            client.request("GET", "test")
        assert exc_info.value.retry_after == 30.0
        client.close()

    def test_timeout_error_is_wrapped(self, httpx_mock, monkeypatch):
        monkeypatch.setattr(generated_client_module.time, "sleep", lambda _: None)
        httpx_mock.add_exception(httpx.TimeoutException("timed out"))
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(generated_client_module.WorkOSTimeoutException):
            client.request("GET", "test")
        client.close()

    def test_connection_error_is_wrapped(self, httpx_mock, monkeypatch):
        monkeypatch.setattr(generated_client_module.time, "sleep", lambda _: None)
        httpx_mock.add_exception(httpx.ConnectError("connect failed"))
        client = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        with pytest.raises(generated_client_module.WorkOSConnectionException):
            client.request("GET", "test")
        client.close()

    def test_documented_import_surface_exposes_resources(self):
        client = WorkOS(api_key="sk_test_123", client_id="client_test")
        assert client.admin_portal is not None
        assert client.api_keys is not None
        assert client.application_client_secrets is not None
        assert client.applications is not None
        assert client.audit_logs is not None
        assert client.authorization is not None
        assert client.connections is not None
        assert client.directories is not None
        assert client.directory_groups is not None
        assert client.directory_users is not None
        assert client.events is not None
        assert client.feature_flags is not None
        assert client.feature_flags.targets is not None
        assert client.multi_factor_auth is not None
        assert client.multi_factor_auth.challenges is not None
        assert client.organization_domains is not None
        assert client.organizations is not None
        assert client.organizations.api_keys is not None
        assert client.organizations.feature_flags is not None
        assert client.permissions is not None
        assert client.pipes is not None
        assert client.radar is not None
        assert client.sso is not None
        assert client.user_management.authentication is not None
        assert client.user_management.cors_origins is not None
        assert client.user_management.data_providers is not None
        assert client.user_management.invitations is not None
        assert client.user_management.jwt_template is not None
        assert client.user_management.magic_auth is not None
        assert client.user_management.multi_factor_authentication is not None
        assert client.user_management.organization_membership is not None
        assert client.user_management.redirect_uris is not None
        assert client.user_management.session_tokens is not None
        assert client.user_management.users is not None
        assert client.user_management_users.authorized_applications is not None
        assert client.user_management_users.feature_flags is not None
        assert client.webhooks is not None
        assert client.widgets is not None
        assert client.workos_connect is not None
        client.close()


@pytest.mark.asyncio
class TestAsyncWorkOSClient:
    async def test_documented_import_surface_exposes_resources(self):
        client = AsyncWorkOS(api_key="sk_test_123", client_id="client_test")
        assert client.admin_portal is not None
        assert client.api_keys is not None
        assert client.application_client_secrets is not None
        assert client.applications is not None
        assert client.audit_logs is not None
        assert client.authorization is not None
        assert client.connections is not None
        assert client.directories is not None
        assert client.directory_groups is not None
        assert client.directory_users is not None
        assert client.events is not None
        assert client.feature_flags is not None
        assert client.feature_flags.targets is not None
        assert client.multi_factor_auth is not None
        assert client.multi_factor_auth.challenges is not None
        assert client.organization_domains is not None
        assert client.organizations is not None
        assert client.organizations.api_keys is not None
        assert client.organizations.feature_flags is not None
        assert client.permissions is not None
        assert client.pipes is not None
        assert client.radar is not None
        assert client.sso is not None
        assert client.user_management.authentication is not None
        assert client.user_management.cors_origins is not None
        assert client.user_management.data_providers is not None
        assert client.user_management.invitations is not None
        assert client.user_management.jwt_template is not None
        assert client.user_management.magic_auth is not None
        assert client.user_management.multi_factor_authentication is not None
        assert client.user_management.organization_membership is not None
        assert client.user_management.redirect_uris is not None
        assert client.user_management.session_tokens is not None
        assert client.user_management.users is not None
        assert client.user_management_users.authorized_applications is not None
        assert client.user_management_users.feature_flags is not None
        assert client.webhooks is not None
        assert client.widgets is not None
        assert client.workos_connect is not None
        await client.close()

    async def test_timeout_error_is_wrapped(self, httpx_mock, monkeypatch):
        async def _sleep(_: float) -> None:
            return None

        monkeypatch.setattr(generated_client_module.asyncio, "sleep", _sleep)
        httpx_mock.add_exception(httpx.TimeoutException("timed out"))
        client = AsyncWorkOS(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        with pytest.raises(generated_client_module.WorkOSTimeoutException):
            await client.request("GET", "test")
        await client.close()

    async def test_connection_error_is_wrapped(self, httpx_mock, monkeypatch):
        async def _sleep(_: float) -> None:
            return None

        monkeypatch.setattr(generated_client_module.asyncio, "sleep", _sleep)
        httpx_mock.add_exception(httpx.ConnectError("connect failed"))
        client = AsyncWorkOS(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        with pytest.raises(generated_client_module.WorkOSConnectionException):
            await client.request("GET", "test")
        await client.close()
