# This file is auto-generated by oagen. Do not edit.


import pytest
from workos import WorkOS, AsyncWorkOS
from tests.generated_helpers import load_fixture

from workos.connections.models import (
    Connection,
    ConnectionsConnectionType,
    ConnectionsOrder,
)
from workos._pagination import AsyncPage, SyncPage
from workos._errors import (
    AuthenticationException,
    NotFoundException,
    RateLimitExceededException,
    ServerException,
)


class TestConnections:
    def test_list(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("list_connection.json"),
        )
        page = workos.connections.list()
        assert isinstance(page, SyncPage)
        assert isinstance(page.data, list)

    def test_list_empty_page(self, workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = workos.connections.list()
        assert isinstance(page, SyncPage)
        assert page.data == []

    def test_list_encodes_query_params(self, workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        workos.connections.list(
            limit=10,
            before="cursor before",
            after="cursor/after",
            order=ConnectionsOrder("normal"),
            connection_type=ConnectionsConnectionType("ADFSSAML"),
            domain="value domain/test",
            organization_id="value organization_id/test",
            search="value search/test",
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["order"] == "normal"
        assert request.url.params["connection_type"] == "ADFSSAML"
        assert request.url.params["domain"] == "value domain/test"
        assert request.url.params["organization_id"] == "value organization_id/test"
        assert request.url.params["search"] == "value search/test"

    def test_get(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("connection.json"),
        )
        result = workos.connections.get("test_id")
        assert isinstance(result, Connection)
        assert result.object == "connection"
        assert result.id == "conn_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/connections/test_id")

    def test_delete(self, workos, httpx_mock):
        httpx_mock.add_response(status_code=204)
        result = workos.connections.delete("test_id")
        assert result is None
        request = httpx_mock.get_request()
        assert request.method == "DELETE"
        assert request.url.path.endswith("/connections/test_id")

    def test_list_unauthorized(self, workos, httpx_mock):
        httpx_mock.add_response(
            status_code=401,
            json={"message": "Unauthorized"},
        )
        with pytest.raises(AuthenticationException):
            workos.connections.list()

    def test_list_not_found(self, httpx_mock):
        workos = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundException):
                workos.connections.list()
        finally:
            workos.close()

    def test_list_rate_limited(self, httpx_mock):
        workos = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededException):
                workos.connections.list()
        finally:
            workos.close()

    def test_list_server_error(self, httpx_mock):
        workos = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerException):
                workos.connections.list()
        finally:
            workos.close()


@pytest.mark.asyncio
class TestAsyncConnections:
    async def test_list(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("list_connection.json"))
        page = await async_workos.connections.list()
        assert isinstance(page, AsyncPage)
        assert isinstance(page.data, list)

    async def test_list_empty_page(self, async_workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = await async_workos.connections.list()
        assert isinstance(page, AsyncPage)
        assert page.data == []

    async def test_list_encodes_query_params(self, async_workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        await async_workos.connections.list(
            limit=10,
            before="cursor before",
            after="cursor/after",
            order=ConnectionsOrder("normal"),
            connection_type=ConnectionsConnectionType("ADFSSAML"),
            domain="value domain/test",
            organization_id="value organization_id/test",
            search="value search/test",
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["order"] == "normal"
        assert request.url.params["connection_type"] == "ADFSSAML"
        assert request.url.params["domain"] == "value domain/test"
        assert request.url.params["organization_id"] == "value organization_id/test"
        assert request.url.params["search"] == "value search/test"

    async def test_get(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("connection.json"))
        result = await async_workos.connections.get("test_id")
        assert isinstance(result, Connection)
        assert result.object == "connection"
        assert result.id == "conn_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/connections/test_id")

    async def test_delete(self, async_workos, httpx_mock):
        httpx_mock.add_response(status_code=204)
        result = await async_workos.connections.delete("test_id")
        assert result is None
        request = httpx_mock.get_request()
        assert request.method == "DELETE"
        assert request.url.path.endswith("/connections/test_id")

    async def test_list_unauthorized(self, async_workos, httpx_mock):
        httpx_mock.add_response(status_code=401, json={"message": "Unauthorized"})
        with pytest.raises(AuthenticationException):
            await async_workos.connections.list()

    async def test_list_not_found(self, httpx_mock):
        workos = AsyncWorkOS(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundException):
                await workos.connections.list()
        finally:
            await workos.close()

    async def test_list_rate_limited(self, httpx_mock):
        workos = AsyncWorkOS(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededException):
                await workos.connections.list()
        finally:
            await workos.close()

    async def test_list_server_error(self, httpx_mock):
        workos = AsyncWorkOS(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerException):
                await workos.connections.list()
        finally:
            await workos.close()
