# This file is auto-generated by oagen. Do not edit.


import pytest
from workos import WorkOSClient, AsyncWorkOSClient
from tests.generated_helpers import load_fixture

from workos.common.models import Group, PaginationOrder
from workos._pagination import AsyncPage, SyncPage
from workos._errors import (
    AuthenticationError,
    BadRequestError,
    NotFoundError,
    RateLimitExceededError,
    ServerError,
    UnprocessableEntityError,
)


class TestUserManagementOrganizationMembershipGroups:
    def test_list_organization_membership_groups(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("list_group.json"),
        )
        page = workos.user_management_organization_membership_groups.list_organization_membership_groups(
            "test_omId"
        )
        assert isinstance(page, SyncPage)
        assert len(page.data) == 1
        assert isinstance(page.data[0], Group)

    def test_list_organization_membership_groups_empty_page(self, workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = workos.user_management_organization_membership_groups.list_organization_membership_groups(
            "test_omId"
        )
        assert isinstance(page, SyncPage)
        assert page.data == []

    def test_list_organization_membership_groups_encodes_query_params(
        self, workos, httpx_mock
    ):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        workos.user_management_organization_membership_groups.list_organization_membership_groups(
            "test_omId",
            limit=10,
            before="cursor before",
            after="cursor/after",
            order=PaginationOrder("value_order"),
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["order"] == "value_order"

    def test_list_organization_membership_groups_with_request_options(
        self, workos, httpx_mock
    ):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        workos.user_management_organization_membership_groups.list_organization_membership_groups(
            "test_omId", request_options={"extra_headers": {"X-Custom": "value"}}
        )
        request = httpx_mock.get_request()
        assert request.headers["X-Custom"] == "value"

    def test_list_organization_membership_groups_unauthorized(self, workos, httpx_mock):
        httpx_mock.add_response(
            status_code=401,
            json={"message": "Unauthorized"},
        )
        with pytest.raises(AuthenticationError):
            workos.user_management_organization_membership_groups.list_organization_membership_groups(
                "test_omId"
            )

    def test_list_organization_membership_groups_not_found(self, httpx_mock):
        workos = WorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundError):
                workos.user_management_organization_membership_groups.list_organization_membership_groups(
                    "test_omId"
                )
        finally:
            workos.close()

    def test_list_organization_membership_groups_rate_limited(self, httpx_mock):
        workos = WorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededError):
                workos.user_management_organization_membership_groups.list_organization_membership_groups(
                    "test_omId"
                )
        finally:
            workos.close()

    def test_list_organization_membership_groups_server_error(self, httpx_mock):
        workos = WorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerError):
                workos.user_management_organization_membership_groups.list_organization_membership_groups(
                    "test_omId"
                )
        finally:
            workos.close()

    def test_list_organization_membership_groups_bad_request(self, httpx_mock):
        workos = WorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=400, json={"message": "Bad request"})
            with pytest.raises(BadRequestError):
                workos.user_management_organization_membership_groups.list_organization_membership_groups(
                    "test_omId"
                )
        finally:
            workos.close()

    def test_list_organization_membership_groups_unprocessable(self, httpx_mock):
        workos = WorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=422, json={"message": "Unprocessable"})
            with pytest.raises(UnprocessableEntityError):
                workos.user_management_organization_membership_groups.list_organization_membership_groups(
                    "test_omId"
                )
        finally:
            workos.close()


class TestAsyncUserManagementOrganizationMembershipGroups:
    @pytest.mark.asyncio
    async def test_list_organization_membership_groups(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("list_group.json"))
        page = await async_workos.user_management_organization_membership_groups.list_organization_membership_groups(
            "test_omId"
        )
        assert isinstance(page, AsyncPage)
        assert len(page.data) == 1
        assert isinstance(page.data[0], Group)

    @pytest.mark.asyncio
    async def test_list_organization_membership_groups_empty_page(
        self, async_workos, httpx_mock
    ):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = await async_workos.user_management_organization_membership_groups.list_organization_membership_groups(
            "test_omId"
        )
        assert isinstance(page, AsyncPage)
        assert page.data == []

    @pytest.mark.asyncio
    async def test_list_organization_membership_groups_encodes_query_params(
        self, async_workos, httpx_mock
    ):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        await async_workos.user_management_organization_membership_groups.list_organization_membership_groups(
            "test_omId",
            limit=10,
            before="cursor before",
            after="cursor/after",
            order=PaginationOrder("value_order"),
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["order"] == "value_order"

    @pytest.mark.asyncio
    async def test_list_organization_membership_groups_with_request_options(
        self, async_workos, httpx_mock
    ):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        await async_workos.user_management_organization_membership_groups.list_organization_membership_groups(
            "test_omId", request_options={"extra_headers": {"X-Custom": "value"}}
        )
        request = httpx_mock.get_request()
        assert request.headers["X-Custom"] == "value"

    @pytest.mark.asyncio
    async def test_list_organization_membership_groups_unauthorized(
        self, async_workos, httpx_mock
    ):
        httpx_mock.add_response(status_code=401, json={"message": "Unauthorized"})
        with pytest.raises(AuthenticationError):
            await async_workos.user_management_organization_membership_groups.list_organization_membership_groups(
                "test_omId"
            )

    @pytest.mark.asyncio
    async def test_list_organization_membership_groups_not_found(self, httpx_mock):
        workos = AsyncWorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundError):
                await workos.user_management_organization_membership_groups.list_organization_membership_groups(
                    "test_omId"
                )
        finally:
            await workos.close()

    @pytest.mark.asyncio
    async def test_list_organization_membership_groups_rate_limited(self, httpx_mock):
        workos = AsyncWorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededError):
                await workos.user_management_organization_membership_groups.list_organization_membership_groups(
                    "test_omId"
                )
        finally:
            await workos.close()

    @pytest.mark.asyncio
    async def test_list_organization_membership_groups_server_error(self, httpx_mock):
        workos = AsyncWorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerError):
                await workos.user_management_organization_membership_groups.list_organization_membership_groups(
                    "test_omId"
                )
        finally:
            await workos.close()

    @pytest.mark.asyncio
    async def test_list_organization_membership_groups_bad_request(self, httpx_mock):
        workos = AsyncWorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=400, json={"message": "Bad request"})
            with pytest.raises(BadRequestError):
                await workos.user_management_organization_membership_groups.list_organization_membership_groups(
                    "test_omId"
                )
        finally:
            await workos.close()

    @pytest.mark.asyncio
    async def test_list_organization_membership_groups_unprocessable(self, httpx_mock):
        workos = AsyncWorkOSClient(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=422, json={"message": "Unprocessable"})
            with pytest.raises(UnprocessableEntityError):
                await workos.user_management_organization_membership_groups.list_organization_membership_groups(
                    "test_omId"
                )
        finally:
            await workos.close()
