# This file is auto-generated by oagen. Do not edit.

import json

import pytest
from workos import WorkOS, AsyncWorkOS
from tests.generated_helpers import load_fixture

from workos.user_management.authentication.models import User
from workos.user_management.users.models import (
    EmailVerification,
    PasswordReset,
    ResetPasswordResponse,
    SendVerificationEmailResponse,
    UserIdentitiesGetItem,
    VerifyEmailResponse,
    UserManagementUsersOrder,
)
from workos._pagination import AsyncPage, SyncPage
from workos._errors import (
    AuthenticationException,
    NotFoundException,
    RateLimitExceededException,
    ServerException,
)


class TestUserManagementUsers:
    def test_get_email_verification(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("email_verification.json"),
        )
        result = workos.user_management.users.get_email_verification("test_id")
        assert isinstance(result, EmailVerification)
        assert result.object == "email_verification"
        assert result.id == "email_verification_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/user_management/email_verification/test_id")

    def test_create_password_reset_token(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("password_reset.json"),
        )
        result = workos.user_management.users.create_password_reset_token(
            email="test_email"
        )
        assert isinstance(result, PasswordReset)
        assert result.object == "password_reset"
        assert result.id == "password_reset_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/user_management/password_reset")
        body = json.loads(request.content)
        assert body["email"] == "test_email"

    def test_reset_password(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("reset_password_response.json"),
        )
        result = workos.user_management.users.reset_password(
            token="test_token", new_password="test_new_password"
        )
        assert isinstance(result, ResetPasswordResponse)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/user_management/password_reset/confirm")
        body = json.loads(request.content)
        assert body["token"] == "test_token"
        assert body["new_password"] == "test_new_password"

    def test_get_password_reset(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("password_reset.json"),
        )
        result = workos.user_management.users.get_password_reset("test_id")
        assert isinstance(result, PasswordReset)
        assert result.object == "password_reset"
        assert result.id == "password_reset_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/user_management/password_reset/test_id")

    def test_list_users(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("list_user.json"),
        )
        page = workos.user_management.users.list_users()
        assert isinstance(page, SyncPage)
        assert isinstance(page.data, list)

    def test_list_users_empty_page(self, workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = workos.user_management.users.list_users()
        assert isinstance(page, SyncPage)
        assert page.data == []

    def test_list_users_encodes_query_params(self, workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        workos.user_management.users.list_users(
            limit=10,
            before="cursor before",
            after="cursor/after",
            order=UserManagementUsersOrder("normal"),
            organization="value organization/test",
            organization_id="value organization_id/test",
            email="value email/test",
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["order"] == "normal"
        assert request.url.params["organization"] == "value organization/test"
        assert request.url.params["organization_id"] == "value organization_id/test"
        assert request.url.params["email"] == "value email/test"

    def test_create(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("user.json"),
        )
        result = workos.user_management.users.create(email="test_email")
        assert isinstance(result, User)
        assert result.object == "user"
        assert result.id == "user_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/user_management/users")
        body = json.loads(request.content)
        assert body["email"] == "test_email"

    def test_get_by_external_id(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("user.json"),
        )
        result = workos.user_management.users.get_by_external_id("test_external_id")
        assert isinstance(result, User)
        assert result.object == "user"
        assert result.id == "user_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith(
            "/user_management/users/external_id/test_external_id"
        )

    def test_get_user(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("user.json"),
        )
        result = workos.user_management.users.get_user("test_id")
        assert isinstance(result, User)
        assert result.object == "user"
        assert result.id == "user_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/user_management/users/test_id")

    def test_update(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("user.json"),
        )
        result = workos.user_management.users.update("test_id")
        assert isinstance(result, User)
        assert result.object == "user"
        assert result.id == "user_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "PUT"
        assert request.url.path.endswith("/user_management/users/test_id")

    def test_delete(self, workos, httpx_mock):
        httpx_mock.add_response(status_code=204)
        result = workos.user_management.users.delete("test_id")
        assert result is None
        request = httpx_mock.get_request()
        assert request.method == "DELETE"
        assert request.url.path.endswith("/user_management/users/test_id")

    def test_email_verification(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("verify_email_response.json"),
        )
        result = workos.user_management.users.email_verification(
            "test_id", code="test_code"
        )
        assert isinstance(result, VerifyEmailResponse)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith(
            "/user_management/users/test_id/email_verification/confirm"
        )
        body = json.loads(request.content)
        assert body["code"] == "test_code"

    def test_send_verification_email(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("send_verification_email_response.json"),
        )
        result = workos.user_management.users.send_verification_email("test_id")
        assert isinstance(result, SendVerificationEmailResponse)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith(
            "/user_management/users/test_id/email_verification/send"
        )

    def test_get_identity(self, workos, httpx_mock):
        httpx_mock.add_response(json=[load_fixture("user_identities_get_item.json")])
        result = workos.user_management.users.get_identity("test_id")
        assert isinstance(result, list)
        assert len(result) == 1
        assert isinstance(result[0], UserIdentitiesGetItem)

    def test_list_sessions(self, workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("list_user_sessions_list_item.json"),
        )
        page = workos.user_management.users.list_sessions("test_id")
        assert isinstance(page, SyncPage)
        assert isinstance(page.data, list)

    def test_list_sessions_empty_page(self, workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = workos.user_management.users.list_sessions("test_id")
        assert isinstance(page, SyncPage)
        assert page.data == []

    def test_list_sessions_encodes_query_params(self, workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        workos.user_management.users.list_sessions(
            "test_id",
            limit=10,
            before="cursor before",
            after="cursor/after",
            order=UserManagementUsersOrder("normal"),
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["order"] == "normal"

    def test_get_email_verification_unauthorized(self, workos, httpx_mock):
        httpx_mock.add_response(
            status_code=401,
            json={"message": "Unauthorized"},
        )
        with pytest.raises(AuthenticationException):
            workos.user_management.users.get_email_verification("test_id")

    def test_get_email_verification_not_found(self, httpx_mock):
        workos = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundException):
                workos.user_management.users.get_email_verification("test_id")
        finally:
            workos.close()

    def test_get_email_verification_rate_limited(self, httpx_mock):
        workos = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededException):
                workos.user_management.users.get_email_verification("test_id")
        finally:
            workos.close()

    def test_get_email_verification_server_error(self, httpx_mock):
        workos = WorkOS(api_key="sk_test_123", client_id="client_test", max_retries=0)
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerException):
                workos.user_management.users.get_email_verification("test_id")
        finally:
            workos.close()


@pytest.mark.asyncio
class TestAsyncUserManagementUsers:
    async def test_get_email_verification(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("email_verification.json"))
        result = await async_workos.user_management.users.get_email_verification(
            "test_id"
        )
        assert isinstance(result, EmailVerification)
        assert result.object == "email_verification"
        assert result.id == "email_verification_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/user_management/email_verification/test_id")

    async def test_create_password_reset_token(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("password_reset.json"))
        result = await async_workos.user_management.users.create_password_reset_token(
            email="test_email"
        )
        assert isinstance(result, PasswordReset)
        assert result.object == "password_reset"
        assert result.id == "password_reset_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/user_management/password_reset")

    async def test_reset_password(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("reset_password_response.json"))
        result = await async_workos.user_management.users.reset_password(
            token="test_token", new_password="test_new_password"
        )
        assert isinstance(result, ResetPasswordResponse)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/user_management/password_reset/confirm")

    async def test_get_password_reset(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("password_reset.json"))
        result = await async_workos.user_management.users.get_password_reset("test_id")
        assert isinstance(result, PasswordReset)
        assert result.object == "password_reset"
        assert result.id == "password_reset_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/user_management/password_reset/test_id")

    async def test_list_users(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("list_user.json"))
        page = await async_workos.user_management.users.list_users()
        assert isinstance(page, AsyncPage)
        assert isinstance(page.data, list)

    async def test_list_users_empty_page(self, async_workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = await async_workos.user_management.users.list_users()
        assert isinstance(page, AsyncPage)
        assert page.data == []

    async def test_list_users_encodes_query_params(self, async_workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        await async_workos.user_management.users.list_users(
            limit=10,
            before="cursor before",
            after="cursor/after",
            order=UserManagementUsersOrder("normal"),
            organization="value organization/test",
            organization_id="value organization_id/test",
            email="value email/test",
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["order"] == "normal"
        assert request.url.params["organization"] == "value organization/test"
        assert request.url.params["organization_id"] == "value organization_id/test"
        assert request.url.params["email"] == "value email/test"

    async def test_create(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("user.json"))
        result = await async_workos.user_management.users.create(email="test_email")
        assert isinstance(result, User)
        assert result.object == "user"
        assert result.id == "user_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/user_management/users")

    async def test_get_by_external_id(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("user.json"))
        result = await async_workos.user_management.users.get_by_external_id(
            "test_external_id"
        )
        assert isinstance(result, User)
        assert result.object == "user"
        assert result.id == "user_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith(
            "/user_management/users/external_id/test_external_id"
        )

    async def test_get_user(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("user.json"))
        result = await async_workos.user_management.users.get_user("test_id")
        assert isinstance(result, User)
        assert result.object == "user"
        assert result.id == "user_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/user_management/users/test_id")

    async def test_update(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("user.json"))
        result = await async_workos.user_management.users.update("test_id")
        assert isinstance(result, User)
        assert result.object == "user"
        assert result.id == "user_01E4ZCR3C56J083X43JQXF3JK5"
        request = httpx_mock.get_request()
        assert request.method == "PUT"
        assert request.url.path.endswith("/user_management/users/test_id")

    async def test_delete(self, async_workos, httpx_mock):
        httpx_mock.add_response(status_code=204)
        result = await async_workos.user_management.users.delete("test_id")
        assert result is None
        request = httpx_mock.get_request()
        assert request.method == "DELETE"
        assert request.url.path.endswith("/user_management/users/test_id")

    async def test_email_verification(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("verify_email_response.json"))
        result = await async_workos.user_management.users.email_verification(
            "test_id", code="test_code"
        )
        assert isinstance(result, VerifyEmailResponse)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith(
            "/user_management/users/test_id/email_verification/confirm"
        )

    async def test_send_verification_email(self, async_workos, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture("send_verification_email_response.json")
        )
        result = await async_workos.user_management.users.send_verification_email(
            "test_id"
        )
        assert isinstance(result, SendVerificationEmailResponse)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith(
            "/user_management/users/test_id/email_verification/send"
        )

    async def test_get_identity(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=[load_fixture("user_identities_get_item.json")])
        result = await async_workos.user_management.users.get_identity("test_id")
        assert isinstance(result, list)
        assert len(result) == 1
        assert isinstance(result[0], UserIdentitiesGetItem)

    async def test_list_sessions(self, async_workos, httpx_mock):
        httpx_mock.add_response(json=load_fixture("list_user_sessions_list_item.json"))
        page = await async_workos.user_management.users.list_sessions("test_id")
        assert isinstance(page, AsyncPage)
        assert isinstance(page.data, list)

    async def test_list_sessions_empty_page(self, async_workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = await async_workos.user_management.users.list_sessions("test_id")
        assert isinstance(page, AsyncPage)
        assert page.data == []

    async def test_list_sessions_encodes_query_params(self, async_workos, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        await async_workos.user_management.users.list_sessions(
            "test_id",
            limit=10,
            before="cursor before",
            after="cursor/after",
            order=UserManagementUsersOrder("normal"),
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["order"] == "normal"

    async def test_get_email_verification_unauthorized(self, async_workos, httpx_mock):
        httpx_mock.add_response(status_code=401, json={"message": "Unauthorized"})
        with pytest.raises(AuthenticationException):
            await async_workos.user_management.users.get_email_verification("test_id")

    async def test_get_email_verification_not_found(self, httpx_mock):
        workos = AsyncWorkOS(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundException):
                await workos.user_management.users.get_email_verification("test_id")
        finally:
            await workos.close()

    async def test_get_email_verification_rate_limited(self, httpx_mock):
        workos = AsyncWorkOS(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededException):
                await workos.user_management.users.get_email_verification("test_id")
        finally:
            await workos.close()

    async def test_get_email_verification_server_error(self, httpx_mock):
        workos = AsyncWorkOS(
            api_key="sk_test_123", client_id="client_test", max_retries=0
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerException):
                await workos.user_management.users.get_email_verification("test_id")
        finally:
            await workos.close()
