# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from workos.organizations.models.create_it_contact import CreateItContact

CreatePasswordResetToken: TypeAlias = CreateItContact
