# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class EmailCompletionSessionAuthenticateRequest:
    """Email Completion Session Authenticate Request model."""

    client_id: str
    """The client ID of the application."""
    client_secret: str
    """The client secret of the application."""
    grant_type: Literal["urn:workos:oauth:grant-type:email-completion"]
    email_completion_token: str
    """The token from the `email_completion_required` response."""
    email: str
    """The email address the user supplied for a profile the identity provider left without one."""
    ip_address: str | None = None
    """The IP address of the user's request."""
    device_id: str | None = None
    """A unique identifier for the device."""
    user_agent: str | None = None
    """The user agent string from the user's browser."""
    signals_id: str | None = None
    """An optional Radar signals ID to correlate client-side signals with this authentication attempt."""

    @classmethod
    def from_dict(
        cls, data: dict[str, Any]
    ) -> EmailCompletionSessionAuthenticateRequest:
        """Deserialize from a dictionary."""
        try:
            return cls(
                client_id=data["client_id"],
                client_secret=data["client_secret"],
                grant_type=data.get(
                    "grant_type", "urn:workos:oauth:grant-type:email-completion"
                ),
                email_completion_token=data["email_completion_token"],
                email=data["email"],
                ip_address=data.get("ip_address"),
                device_id=data.get("device_id"),
                user_agent=data.get("user_agent"),
                signals_id=data.get("signals_id"),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("EmailCompletionSessionAuthenticateRequest", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        result["client_id"] = self.client_id
        result["client_secret"] = self.client_secret
        result["grant_type"] = self.grant_type
        result["email_completion_token"] = self.email_completion_token
        result["email"] = self.email
        if self.ip_address is not None:
            result["ip_address"] = self.ip_address
        if self.device_id is not None:
            result["device_id"] = self.device_id
        if self.user_agent is not None:
            result["user_agent"] = self.user_agent
        if self.signals_id is not None:
            result["signals_id"] = self.signals_id
        return result
