# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional
from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class MagicAuthSendMagicAuthCodeAndReturnResponse:
    """Magic Auth Send Magic Auth Code And Return Response model."""

    radar_auth_attempt_id: Optional[str] = None
    """The ID of the Radar authentication attempt created for this request when Radar is enabled. Pass this value to the authenticate endpoint to associate the subsequent authentication with this Radar attempt."""

    @classmethod
    def from_dict(
        cls, data: Dict[str, Any]
    ) -> "MagicAuthSendMagicAuthCodeAndReturnResponse":
        """Deserialize from a dictionary."""
        try:
            return cls(
                radar_auth_attempt_id=data.get("radar_auth_attempt_id"),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("MagicAuthSendMagicAuthCodeAndReturnResponse", e)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        if self.radar_auth_attempt_id is not None:
            result["radar_auth_attempt_id"] = self.radar_auth_attempt_id
        return result
