# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class UpdateJWTTemplate:
    """Update JWT Template model."""

    content: str
    """The JWT template content as a Liquid template string."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> UpdateJWTTemplate:
        """Deserialize from a dictionary."""
        try:
            return cls(
                content=data["content"],
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("UpdateJWTTemplate", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        result["content"] = self.content
        return result
