# This file is auto-generated by oagen. Do not edit.

from typing_extensions import TypeAlias
from .reset_password_response import ResetPasswordResponse

VerifyEmailResponse: TypeAlias = ResetPasswordResponse
