# This file is auto-generated by oagen. Do not edit.

from ._resource import AsyncOrganizationDomains as AsyncOrganizationDomains
from ._resource import OrganizationDomains as OrganizationDomains
from .models import *
