# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class DirectorySyncResponse:
    """Directory Sync Response model."""

    status: Literal["queued"]
    """The sync request was queued for asynchronous processing. This does not indicate that the sync has started or completed."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DirectorySyncResponse:
        """Deserialize from a dictionary."""
        try:
            return cls(
                status=data.get("status", "queued"),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("DirectorySyncResponse", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        result["status"] = self.status
        return result
