# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias
from workos.user_management.models.api_keys_order import ApiKeysOrder

AuthorizationOrder: TypeAlias = ApiKeysOrder
__all__ = ["AuthorizationOrder"]
