# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional
from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class RemoveRole:
    """Remove Role model."""

    role_slug: str
    """The slug of the role to remove."""
    resource_id: Optional[str] = None
    """The ID of the resource. Use either this or `resource_external_id` and `resource_type_slug`."""
    resource_external_id: Optional[str] = None
    """The external ID of the resource. Requires `resource_type_slug`."""
    resource_type_slug: Optional[str] = None
    """The resource type slug. Required with `resource_external_id`."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "RemoveRole":
        """Deserialize from a dictionary."""
        try:
            return cls(
                role_slug=data["role_slug"],
                resource_id=data.get("resource_id"),
                resource_external_id=data.get("resource_external_id"),
                resource_type_slug=data.get("resource_type_slug"),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("RemoveRole", e)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["role_slug"] = self.role_slug
        if self.resource_id is not None:
            result["resource_id"] = self.resource_id
        if self.resource_external_id is not None:
            result["resource_external_id"] = self.resource_external_id
        if self.resource_type_slug is not None:
            result["resource_type_slug"] = self.resource_type_slug
        return result
