# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class CreateUserOrganizationMembership:
    """Create User Organization Membership model."""

    user_id: str
    """The ID of the [user](https://workos.com/docs/reference/authkit/user)."""
    organization_id: str
    """The ID of the [organization](https://workos.com/docs/reference/organization) which the user belongs to."""
    role_slug: str | None = None
    """A single role identifier. Defaults to `member` or the explicit default role. Mutually exclusive with `role_slugs`."""
    role_slugs: list[str] | None = None
    """An array of role identifiers. Limited to one role when Multiple Roles is disabled. Mutually exclusive with `role_slug`."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CreateUserOrganizationMembership:
        """Deserialize from a dictionary."""
        try:
            return cls(
                user_id=data["user_id"],
                organization_id=data["organization_id"],
                role_slug=data.get("role_slug"),
                role_slugs=data.get("role_slugs"),
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("CreateUserOrganizationMembership", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        result["user_id"] = self.user_id
        result["organization_id"] = self.organization_id
        if self.role_slug is not None:
            result["role_slug"] = self.role_slug
        if self.role_slugs is not None:
            result["role_slugs"] = self.role_slugs
        return result
