# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List, Literal
from workos._errors import WorkOSError
from workos._types import _parse_datetime
from workos.common.models import WebhookEndpointJsonStatus


@dataclass(slots=True)
class WebhookEndpointJson:
    """Webhook Endpoint Json model."""

    object: Literal["webhook_endpoint"]
    """Distinguishes the Webhook Endpoint object."""
    id: str
    """Unique identifier of the Webhook Endpoint."""
    endpoint_url: str
    """The URL to which webhooks are sent."""
    secret: str
    """The secret used to sign webhook payloads."""
    status: "WebhookEndpointJsonStatus"
    """Whether the Webhook Endpoint is enabled or disabled."""
    events: List[str]
    """The events that the Webhook Endpoint is subscribed to."""
    created_at: datetime
    """An ISO 8601 timestamp."""
    updated_at: datetime
    """An ISO 8601 timestamp."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "WebhookEndpointJson":
        """Deserialize from a dictionary."""
        try:
            return cls(
                object=data["object"],
                id=data["id"],
                endpoint_url=data["endpoint_url"],
                secret=data["secret"],
                status=WebhookEndpointJsonStatus(data["status"]),
                events=data["events"],
                created_at=_parse_datetime(data["created_at"]),
                updated_at=_parse_datetime(data["updated_at"]),
            )
        except (KeyError, ValueError) as e:
            raise WorkOSError(
                f"Unexpected API response while parsing WebhookEndpointJson: {e!s}"
            ) from e

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["object"] = self.object
        result["id"] = self.id
        result["endpoint_url"] = self.endpoint_url
        result["secret"] = self.secret
        result["status"] = self.status
        result["events"] = self.events
        result["created_at"] = self.created_at.isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")
        result["updated_at"] = self.updated_at.isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")
        return result
