# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional
from workos._errors import BaseRequestException


@dataclass(slots=True)
class UserSessionsImpersonator:
    """Information about the impersonator if this session was created via impersonation."""

    email: str
    """The email address of the WorkOS Dashboard user who is impersonating the user."""
    reason: Optional[str]
    """The justification the impersonator gave for impersonating the user."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "UserSessionsImpersonator":
        """Deserialize from a dictionary."""
        try:
            return cls(
                email=data["email"],
                reason=data["reason"],
            )
        except (KeyError, ValueError) as e:
            raise BaseRequestException(
                f"Unexpected API response while parsing UserSessionsImpersonator: {e!s}"
            ) from e

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["email"] = self.email
        if self.reason is not None:
            result["reason"] = self.reason
        else:
            result["reason"] = None
        return result
