# This file is auto-generated by oagen. Do not edit.

from .connections_connection_type import ConnectionsConnectionType

ConnectionsConnectionTypeLiteral = ConnectionsConnectionType
__all__ = ["ConnectionsConnectionTypeLiteral"]
