# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, Literal, Optional
from workos._errors import BaseRequestException
from workos.common.models import OrganizationDomainStandAloneState
from workos.common.models import OrganizationDomainStandAloneVerificationStrategy


@dataclass(slots=True)
class OrganizationDomainStandAlone:
    """Organization Domain Stand Alone model."""

    object: Literal["organization_domain"]
    """Distinguishes the organization domain object."""
    id: str
    """Unique identifier of the organization domain."""
    organization_id: str
    """ID of the parent Organization."""
    domain: str
    """Domain for the organization domain."""
    created_at: datetime
    """An ISO 8601 timestamp."""
    updated_at: datetime
    """An ISO 8601 timestamp."""
    state: Optional["OrganizationDomainStandAloneState"] = None
    """Verification state of the domain."""
    verification_prefix: Optional[str] = None
    """The prefix used in DNS verification."""
    verification_token: Optional[str] = None
    """Validation token to be used in DNS TXT record."""
    verification_strategy: Optional[
        "OrganizationDomainStandAloneVerificationStrategy"
    ] = None
    """Strategy used to verify the domain."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "OrganizationDomainStandAlone":
        """Deserialize from a dictionary."""
        try:
            return cls(
                object=data["object"],
                id=data["id"],
                organization_id=data["organization_id"],
                domain=data["domain"],
                created_at=datetime.fromisoformat(
                    data["created_at"].replace("Z", "+00:00")
                ),
                updated_at=datetime.fromisoformat(
                    data["updated_at"].replace("Z", "+00:00")
                ),
                state=OrganizationDomainStandAloneState(_v)
                if (_v := data.get("state")) is not None
                else None,
                verification_prefix=data.get("verification_prefix"),
                verification_token=data.get("verification_token"),
                verification_strategy=OrganizationDomainStandAloneVerificationStrategy(
                    _v
                )
                if (_v := data.get("verification_strategy")) is not None
                else None,
            )
        except (KeyError, ValueError) as e:
            raise BaseRequestException(
                f"Unexpected API response while parsing OrganizationDomainStandAlone: {e!s}"
            ) from e

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["object"] = self.object
        result["id"] = self.id
        result["organization_id"] = self.organization_id
        result["domain"] = self.domain
        result["created_at"] = self.created_at.isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")
        result["updated_at"] = self.updated_at.isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")
        if self.state is not None:
            result["state"] = self.state
        if self.verification_prefix is not None:
            result["verification_prefix"] = self.verification_prefix
        if self.verification_token is not None:
            result["verification_token"] = self.verification_token
        if self.verification_strategy is not None:
            result["verification_strategy"] = self.verification_strategy
        return result
