# This file is auto-generated by oagen. Do not edit.

"""Enumeration of user management authentication screen hint values."""

from __future__ import annotations

from enum import Enum
from typing import Optional
from typing_extensions import Literal, TypeAlias


class UserManagementAuthenticationScreenHint(str, Enum):
    """Known values for UserManagementAuthenticationScreenHint."""

    SIGN_UP = "sign-up"
    SIGN_IN = "sign-in"

    @classmethod
    def _missing_(
        cls, value: object
    ) -> Optional["UserManagementAuthenticationScreenHint"]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


UserManagementAuthenticationScreenHintLiteral: TypeAlias = Literal["sign-up", "sign-in"]
