from typing import Literal


ConnectionType = Literal[
    "ADFSSAML",
    "AdpOidc",
    "AppleOAuth",
    "Auth0SAML",
    "AzureSAML",
    "CasSAML",
    "CloudflareSAML",
    "ClassLinkSAML",
    "CyberArkSAML",
    "DuoSAML",
    "GenericOIDC",
    "GenericSAML",
    "GitHubOAuth",
    "GoogleOAuth",
    "GoogleSAML",
    "JumpCloudSAML",
    "KeycloakSAML",
    "LastPassSAML",
    "LoginGovOidc",
    "MagicLink",
    "MicrosoftOAuth",
    "MiniOrangeSAML",
    "NetIqSAML",
    "OktaSAML",
    "OneLoginSAML",
    "OracleSAML",
    "PingFederateSAML",
    "PingOneSAML",
    "RipplingSAML",
    "SalesforceSAML",
    "ShibbolethGenericSAML",
    "ShibbolethSAML",
    "SimpleSamlPhpSAML",
    "VMwareSAML",
]
