# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from typing import TYPE_CHECKING, List, Optional

if TYPE_CHECKING:
    from .._client import AsyncWorkOSClient, WorkOSClient

from .models import Event
from .models import EventsOrder
from .._pagination import AsyncPage, SyncPage
from .._types import RequestOptions


class Events:
    """Events API resources."""

    def __init__(self, client: "WorkOSClient") -> None:
        self._client = client

    def list_events(
        self,
        *,
        limit: Optional[int] = None,
        before: Optional[str] = None,
        after: Optional[str] = None,
        order: Optional[EventsOrder] = None,
        events: Optional[List[str]] = None,
        range_start: Optional[str] = None,
        range_end: Optional[str] = None,
        organization_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[Event]:
        """List events

        List events for the current environment.

                Args:
                    events: Filter events by one or more event types (e.g. `dsync.user.created`).
                    range_start: ISO-8601 date string to filter events created after this date.
                    range_end: ISO-8601 date string to filter events created before this date.
                    organization_id: Filter events by the [Organization](https://workos.com/docs/reference/organization) that the event is associated with.
                    limit: Maximum number of records to return.
                    before: Pagination cursor for previous page.
                    after: Pagination cursor for next page.
                    order: Sort order.
                    request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

                Returns:
                    SyncPage[Event]

                Raises:
                    BadRequestException: If the request is malformed (400).
                    UnprocessableEntityException: If the request data is unprocessable (422).
                    AuthenticationException: If the API key is invalid (401).
                    RateLimitExceededException: If rate limited (429).
                    ServerException: If the server returns a 5xx error.
        """
        params = {
            k: v
            for k, v in {
                "limit": limit,
                "before": before,
                "after": after,
                "order": order.value if order else None,
                "events": events,
                "range_start": range_start,
                "range_end": range_end,
                "organization_id": organization_id,
            }.items()
            if v is not None
        }
        return self._client.request_page(
            method="get",
            path="events",
            model=Event,
            params=params,
            request_options=request_options,
        )

    list = list_events


class AsyncEvents:
    """Events API resources (async)."""

    def __init__(self, client: "AsyncWorkOSClient") -> None:
        self._client = client

    async def list_events(
        self,
        *,
        limit: Optional[int] = None,
        before: Optional[str] = None,
        after: Optional[str] = None,
        order: Optional[EventsOrder] = None,
        events: Optional[List[str]] = None,
        range_start: Optional[str] = None,
        range_end: Optional[str] = None,
        organization_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncPage[Event]:
        """List events

        List events for the current environment.

                Args:
                    events: Filter events by one or more event types (e.g. `dsync.user.created`).
                    range_start: ISO-8601 date string to filter events created after this date.
                    range_end: ISO-8601 date string to filter events created before this date.
                    organization_id: Filter events by the [Organization](https://workos.com/docs/reference/organization) that the event is associated with.
                    limit: Maximum number of records to return.
                    before: Pagination cursor for previous page.
                    after: Pagination cursor for next page.
                    order: Sort order.
                    request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

                Returns:
                    AsyncPage[Event]

                Raises:
                    BadRequestException: If the request is malformed (400).
                    UnprocessableEntityException: If the request data is unprocessable (422).
                    AuthenticationException: If the API key is invalid (401).
                    RateLimitExceededException: If rate limited (429).
                    ServerException: If the server returns a 5xx error.
        """
        params = {
            k: v
            for k, v in {
                "limit": limit,
                "before": before,
                "after": after,
                "order": order.value if order else None,
                "events": events,
                "range_start": range_start,
                "range_end": range_end,
                "organization_id": organization_id,
            }.items()
            if v is not None
        }
        return await self._client.request_page(
            method="get",
            path="events",
            model=Event,
            params=params,
            request_options=request_options,
        )

    list = list_events
