# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from workos._errors import WorkOSError
from workos._types import _parse_datetime


@dataclass(slots=True)
class ConnectApplication:
    """Connect Application model."""

    object: Literal["connect_application"]
    """Distinguishes the connect application object."""
    id: str
    """The unique ID of the connect application."""
    client_id: str
    """The client ID of the connect application."""
    description: Optional[str]
    """A description of the connect application."""
    name: str
    """The name of the connect application."""
    scopes: List[str]
    """The scopes available for this application."""
    created_at: datetime
    """An ISO 8601 timestamp."""
    updated_at: datetime
    """An ISO 8601 timestamp."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ConnectApplication":
        """Deserialize from a dictionary."""
        try:
            return cls(
                object=data["object"],
                id=data["id"],
                client_id=data["client_id"],
                description=data["description"],
                name=data["name"],
                scopes=data["scopes"],
                created_at=_parse_datetime(data["created_at"]),
                updated_at=_parse_datetime(data["updated_at"]),
            )
        except (KeyError, ValueError) as e:
            raise WorkOSError(
                f"Unexpected API response while parsing ConnectApplication: {e!s}"
            ) from e

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["object"] = self.object
        result["id"] = self.id
        result["client_id"] = self.client_id
        if self.description is not None:
            result["description"] = self.description
        else:
            result["description"] = None
        result["name"] = self.name
        result["scopes"] = self.scopes
        result["created_at"] = self.created_at.isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")
        result["updated_at"] = self.updated_at.isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")
        return result
