# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict
from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class CreateApplicationSecret:
    """Create Application Secret model."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "CreateApplicationSecret":
        """Deserialize from a dictionary."""
        try:
            return cls()
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("CreateApplicationSecret", e)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        return result
