# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import cast
from typing import Any, Dict, List, Literal, Optional
from workos._errors import BaseRequestException

from .flag_owner import FlagOwner


@dataclass(slots=True)
class Flag:
    """Flag model."""

    object: Literal["feature_flag"]
    """Distinguishes the Feature Flag object."""
    id: str
    """Unique identifier of the Feature Flag."""
    slug: str
    """A unique key to reference the Feature Flag."""
    name: str
    """A descriptive name for the Feature Flag. This field does not need to be unique."""
    description: Optional[str]
    """A description for the Feature Flag."""
    owner: Optional["FlagOwner"]
    """The owner of the Feature Flag."""
    tags: List[str]
    """Labels assigned to the Feature Flag for categorizing and filtering."""
    enabled: bool
    """Specifies whether the Feature Flag is active for the current environment."""
    default_value: bool
    """The value returned for users and organizations who don't match any configured targeting rules."""
    created_at: datetime
    """An ISO 8601 timestamp."""
    updated_at: datetime
    """An ISO 8601 timestamp."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Flag":
        """Deserialize from a dictionary."""
        try:
            return cls(
                object=data["object"],
                id=data["id"],
                slug=data["slug"],
                name=data["name"],
                description=data["description"],
                owner=FlagOwner.from_dict(cast(Dict[str, Any], _v))
                if (_v := data["owner"]) is not None
                else None,
                tags=data["tags"],
                enabled=data["enabled"],
                default_value=data["default_value"],
                created_at=datetime.fromisoformat(
                    data["created_at"].replace("Z", "+00:00")
                ),
                updated_at=datetime.fromisoformat(
                    data["updated_at"].replace("Z", "+00:00")
                ),
            )
        except (KeyError, ValueError) as e:
            raise BaseRequestException(
                f"Unexpected API response while parsing Flag: {e!s}"
            ) from e

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["object"] = self.object
        result["id"] = self.id
        result["slug"] = self.slug
        result["name"] = self.name
        if self.description is not None:
            result["description"] = self.description
        else:
            result["description"] = None
        if self.owner is not None:
            result["owner"] = self.owner.to_dict()
        else:
            result["owner"] = None
        result["tags"] = self.tags
        result["enabled"] = self.enabled
        result["default_value"] = self.default_value
        result["created_at"] = self.created_at.isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")
        result["updated_at"] = self.updated_at.isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")
        return result
