# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, Optional
from workos._errors import BaseRequestException
from workos.common.models import AuditLogConfigurationLogStreamState
from workos.common.models import AuditLogConfigurationLogStreamType


@dataclass(slots=True)
class AuditLogConfigurationLogStream:
    """The Audit Log Stream currently configured for the organization, if any."""

    id: str
    """Unique identifier of the Audit Log Stream."""
    type: "AuditLogConfigurationLogStreamType"
    """The type of the Audit Log Stream destination."""
    state: "AuditLogConfigurationLogStreamState"
    """The current state of the Audit Log Stream."""
    last_synced_at: Optional[str]
    """ISO-8601 timestamp of when the last event was successfully synced, or null if no events have been synced."""
    created_at: datetime
    """An ISO 8601 timestamp."""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AuditLogConfigurationLogStream":
        """Deserialize from a dictionary."""
        try:
            return cls(
                id=data["id"],
                type=AuditLogConfigurationLogStreamType(data["type"]),
                state=AuditLogConfigurationLogStreamState(data["state"]),
                last_synced_at=data["last_synced_at"],
                created_at=datetime.fromisoformat(
                    data["created_at"].replace("Z", "+00:00")
                ),
            )
        except (KeyError, ValueError) as e:
            raise BaseRequestException(
                f"Unexpected API response while parsing AuditLogConfigurationLogStream: {e!s}"
            ) from e

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        result: Dict[str, Any] = {}
        result["id"] = self.id
        result["type"] = self.type
        result["state"] = self.state
        if self.last_synced_at is not None:
            result["last_synced_at"] = self.last_synced_at
        else:
            result["last_synced_at"] = None
        result["created_at"] = self.created_at.isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")
        return result
