# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class CreateItContact:
    """Create It Contact model."""

    email: str
    """The email address of the IT contact."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CreateItContact:
        """Deserialize from a dictionary."""
        try:
            return cls(
                email=data["email"],
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("CreateItContact", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        result["email"] = self.email
        return result
