# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from workos._types import _raise_deserialize_error


@dataclass(slots=True)
class ItContactListListMetadata:
    """Pagination cursors for navigating between pages of results."""

    before: str | None
    """An object ID that defines your place in the list. When the ID is not present, you are at the start of the list."""
    after: str | None
    """An object ID that defines your place in the list. When the ID is not present, you are at the end of the list."""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ItContactListListMetadata:
        """Deserialize from a dictionary."""
        try:
            return cls(
                before=data["before"],
                after=data["after"],
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("ItContactListListMetadata", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        result: dict[str, Any] = {}
        if self.before is not None:
            result["before"] = self.before
        else:
            result["before"] = None
        if self.after is not None:
            result["after"] = self.after
        else:
            result["after"] = None
        return result
