# This file is auto-generated by oagen. Do not edit.

from ._resource import AsyncAuthorization as AsyncAuthorization
from ._resource import Authorization as Authorization
from ._resource import ParentByExternalId as ParentByExternalId
from ._resource import ParentById as ParentById
from ._resource import ParentResourceByExternalId as ParentResourceByExternalId
from ._resource import ParentResourceById as ParentResourceById
from ._resource import ResourceTargetByExternalId as ResourceTargetByExternalId
from ._resource import ResourceTargetById as ResourceTargetById
from .models import *
