name: Python Lint

on:
  push:
    branches:
      - "main"
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Python lint and typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # 6.1.0
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # 8.3.2
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --only-group lint --only-group type_check

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Lint
        run: uv run ruff check --extend-exclude .devbox

      - name: Type check
        run: uv run pyright
