name: Python Lint

on:
  push:
    branches:
      - "main"
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Python lint and typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # 7.6.0
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --only-group lint --only-group type_check

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Lint
        run: uv run ruff check --extend-exclude .devbox

      - name: Type check
        run: uv run pyright
