name: Release

on:
  # Support manually pushing a new release
  workflow_dispatch: {}
  # Trigger when a release or pre-release is published
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          pip install -e .[dev]

      - name: Test
        run: |
          python -m pytest

      - name: Build
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
